### ISSUE TITLE
SM2密钥交换

### ISSUE THREAD

**Issue by wangwei3441855** [Tencent/TencentKonaSMSuite#117]
调用密钥交换 算出来的key不一样
![image](https://user-images.githubusercontent.com/28972058/213065093-9ea9d9e5-dec9-4739-8978-6a075211ba50.png)

**Comment by wangwei3441855** [comment]
> 调用密钥交换 算出来的key不一样 ![image](https://user-images.githubusercontent.com/28972058/213065093-9ea9d9e5-dec9-4739-8978-6a075211ba50.png)

交互双方A与B只能有一个是发起方(initiator)。
如果A是发起方(isInitiator = true)，那么B就应该是响应方(isInitiator = false)。

**Comment by johnshajiang** [comment]
看来你已经解决了这个问题 ^_^
