### ISSUE TITLE
Parse X.509-encoded public key

### ISSUE THREAD

**Issue by jsonwan** [Tencent/TencentKonaSMSuite#145]
应用场景：直接使用SM2对字节数据进行加密，公私钥数据使用如下方式生成：
```
tongsuo ecparam -genkey -name SM2 -out leaf.key
# 基于 leaf.key 生成公钥
tongsuo ec -in leaf.key -pubout -out leaf-pubilc.key
cat leaf-pubilc.key
```
生成的公钥文件内容如下：
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoEcz1UBgi0DQgAE8BHoyDr91ptaoN0QRxvYElxdgxzI
WBTynLUqHouCbT2WD03776IFiEWSi1RdmIq7VvE7f8rpvwosDc/timPkcg==
-----END PUBLIC KEY-----
希望能提供工具类把其中的公钥解析出来。

**Comment by johnshajiang** [comment]
上面的公钥的格式是基于X.509规范RFC 5280中的SubjectPublicKeyInfo
```
   SubjectPublicKeyInfo  ::=  SEQUENCE  {
        algorithm            AlgorithmIdentifier,
        subjectPublicKey     BIT STRING  }
```
