### ISSUE TITLE
如何使用tlsv1.2的 TLS_ECDHE_SM4_CBC_SM3 (0xE011)密码套件?

### ISSUE THREAD

**Issue by zhk56** [Tencent/TencentKonaSMSuite#174]
使用SSLInsts.getSSLContext("TLCP")得出TLCP_ECDHE_SM4_CBC_SM3套件,相似的,但不是一个,
使用SSLInsts.getSSLContext("TLS")也不支持此套件.

**Comment by johnshajiang** [comment]
> 使用SSLInsts.getSSLContext("TLCP")得出TLCP_ECDHE_SM4_CBC_SM3套件,相似的,但不是一个

在我们的实现中，ECDHE_SM4_CBC_SM3 (0xE011)仅用于TLCP，其ECDHE算法实际为国标的SM2密钥交换协议，而非国际上通行的ECDH算法。

> 使用SSLInsts.getSSLContext("TLS")也不支持此套件

我们确实没有为TLS 1.2实现所谓的TLS_ECDHE_SM4_CBC_SM3密码套件。似乎没有特定的规范或标准定义了这个套件。0xE011这个ID应该只能用于TLCP协议中的ECDHE_SM4_CBC_SM3。

另外，你可能已经了解到，我们实现了RFC 8998，以支持在TLS 1.3协议中使用国密算法。

**Comment by zhk56** [comment]
对的,我已了解并在使用,谢谢回答
