### ISSUE TITLE
请教一下:kona-ssl,kona-crypto,kona-pkix这些jar包,有没有使用时间限制?是永久免费使用么?

### ISSUE THREAD

**Issue by zhk56** [Tencent/TencentKonaSMSuite#184]
kona-ssl.jar,kona-crypto.jar,kona-pkix.jar这些依赖包:
1,有没有使用时间限制?是永久免费使用么?
2,我看贵公司的签名是5年有效期,那么签名过期后贵公司会继续续签么?
3,请问向oracel申请证书签名贵公司用了大概多久时间呢?
4,jar包中的签名是为了重写或者修改jdk原生代码的授权么?
5,我使用贵公司的源代码,使用gradle生成jar包,引入项目中,不可以使用,怀疑是由于META-INF文件夹下,没有对应rsa和文件签名的原因,可以解答下原因么?如果我想让其正常使用,该如何去做?

**Comment by johnshajiang** [comment]
> 1,有没有使用时间限制?是永久免费使用么?

基于GPL v2 with Classpath Exception许可协议使用，没有时间限制。

> 2,我看贵公司的签名是5年有效期,那么签名过期后贵公司会继续续签么?

我们会长期维护这个项目，证书到期之前就会申请请证书。
不过，证书到期之后并不影响原有jar文件的使用，所以不必担心证书过期的问题。

> 3,请问向oracel申请证书签名贵公司用了大概多久时间呢?

第一次申请时大约花了不到两周时间。

> 4,jar包中的签名是为了重写或者修改jdk原生代码的授权么?

该签名只是为了确保这些jar可以工作在Oracle JDK上，与代码的许可协议无关。

> 5,我使用贵公司的源代码,使用gradle生成jar包,引入项目中,不可以使用,怀疑是由于META-INF文件夹下,没有对应rsa和文件签名的原因,可以解答下原因么?如果我想让其正常使用,该如何去做?

如果你的应用程序的包名不是com.tencent.kona，应该没有问题。
如果不是这种情况，请展示详细的异常信息以便于分析原因。
