### ISSUE TITLE
后续提问:<请教一下:kona-ssl,kona-crypto,kona-pkix这些jar包,有没有使用时间限制?是永久免费使用么?>

### ISSUE THREAD

**Issue by zhk56** [Tencent/TencentKonaSMSuite#185]
首先十分感谢您百忙之中解答我之前的疑惑,也很感谢kona这个项目!
下列为执行命令: jarsigner -verify -verbose .\kona-ssl-1.0.4.jar后响应的内容:
[
jar 已验证。

警告:
此 jar 包含其证书链无效的条目。原因: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
此 jar 包含的签名没有时间戳。如果没有时间戳, 则在其中任一签名者证书到期 (最早为 2027-10-27) 之后, 用户可能无法验证此 jar。

有关详细信息, 请使用 -verbose 和 -certs 选项重新运行。

签名者证书将于 2027-10-27 到期。]
请问:
1,为什么显示2027-10-27 到期,我部署的项目,到这个节点后还能正常使用贵公司jar包的功能么?
2,我将此项目的源代码通过gradle打包,打包后每个jar包内META-INF文件夹下,没有对应rsa文件,和签名文件,我该如何将源代码代码并且生成对应的rsa文件和签名文件呢?

**Comment by johnshajiang** [comment]
> 1,为什么显示2027-10-27 到期,我部署的项目,到这个节点后还能正常使用贵公司jar包的功能么?

Oracle是在2022年10月27日为我们颁发的证书，证书有效期是5年。
证书过期之后，jar依然可以正常使用。
不过，我们肯定会在过期之前，再申请一个新证书。
Oracle只是希望通过这种方式能够了解到这些Provider还处于恰当的维护之中。

> 2,我将此项目的源代码通过gradle打包,打包后每个jar包内META-INF文件夹下,没有对应rsa文件,和签名文件,我该如何将源代码代码并且生成对应的rsa文件和签名文件呢?

你应该只需要直接使用我们发布的已签名jar文件，而并不需要自己去构建那些jar。
对jar进行签名，需要使用一个私钥。具体到此处，这个私钥是与Oracle颁发给我们的证书所对应的私钥。
毫无疑问，这个私钥是保密的。

如果你要直接使用或修改本项目的源代码，那么需要遵循`GPL v2 with Classpath Exception`许可协议。

你也可以使用自己的私钥对jar文件进行签名，但这些jar肯定是无法运行在Oracle JDK上的。
Oracle JDK会对jar的签名进行验证，以确保它所关联的证书（公钥）是由`Oracle JCE Code Signing Certification Authority`颁发的。

**Comment by zhk56** [comment]
好的,感谢告知,再次感谢
