### ISSUE TITLE
请问下为什么在jdk_11会报错？？？

### ISSUE THREAD

**Issue by coasline** [Tencent/TencentKonaSMSuite#188]
![image](https://user-images.githubusercontent.com/3956032/230542392-291ea668-1010-4b07-ab9f-57d61a5ac873.png)
请问下是不是缺少什么东西？？

**Comment by coasline** [comment]
代码如下图
![image](https://user-images.githubusercontent.com/3956032/230542581-cb91ea63-56bc-44f6-98de-950e47352614.png)

**Comment by coasline** [comment]
详细错误如下，
![image](https://user-images.githubusercontent.com/3956032/230542687-b432eaf1-0b06-4e38-b238-8c5374c1b1e7.png)
急求解决，谢谢

**Comment by zhk56** [comment]
看第一个异常提示bc的错误,是否引入的是新版本的bc依赖?
看最后的报错信息包含bootstrap,试下改成appliction?目前我用1.8.0_251以上包括11都是正常的,在openjdk1.8.0_252也是正常的

**Comment by johnshajiang** [comment]
第一张图片中的类是BouncyCastle中的，与TencentKonaSMSuite无关。
如果仓库中使用了BouncyCastle，请关注它可能造成的影响。毕竟，它也提供了国密算法。

**Comment by johnshajiang** [comment]
对于第三图片中的异常，也没看出来与TencentKonaSMSuite有何关系。

**Comment by coasline** [comment]
非常感谢帮忙。
![image](https://user-images.githubusercontent.com/3956032/230780962-ccf1e0f3-7e57-4a5c-bab9-704ce5ca0b63.png)
整个项目工程并未使用BC库，并且该项目已经是APPLICATION，确认是运行到SSLCONTEXT.GETSOCKETFACTORY()报错，而且是在JDK11的环境下报错，同样的代码在JDK1.8_291不报错。

**Comment by johnshajiang** [comment]
@coasline 
请问，你是用的该国密套件的哪个版本？
从1.0.5版开始，该国密套件已经完全不再依赖BouncyCastle了。
建议使用最新版1.0.7.1。

**Comment by coasline** [comment]
好的谢谢。我用的是1.0.4.，我改成最新的1.0.7.1试下。还有就是只使用 Security.insertProviderAt(new KonaProvider(), 1);好像调  SSLContext context = SSLContext.getInstance("TLCPv1.1", "KonaSSL");会报错，我都是要改成 Security.insertProviderAt(new KonaCryptoProvider(), 1);
        Security.insertProviderAt(new KonaPKIXProvider(), 2);
        Security.insertProviderAt(new KonaSSLProvider(), 3);才正常

**Comment by johnshajiang** [comment]
> 还有就是只使用 Security.insertProviderAt(new KonaProvider(), 1);好像调 SSLContext context = SSLContext.getInstance("TLCPv1.1", "KonaSSL");会报错

如果你要使用`KonaProvider`，那么在代码中要提供的Provider名称应该为`Kona`，而不再需要`KonaCrypto`，`KonaPKIX`和`KonaSSL`。如下所示，
```
SSLContext.getInstance("TLCPv1.1", "Kona")
```

**Comment by coasline** [comment]
非常感谢帮忙
