### ISSUE TITLE
master 分支 SM4Test.java testSpec() 执行异常

### ISSUE THREAD

**Issue by KevinnChan** [Tencent/TencentKonaSMSuite#202]
起因是启动了一个Netty Server, 使用postman发送请求异常 ; debug发现 SM4/128 cipher 不可用
![WX20230419-180600@2x](https://user-images.githubusercontent.com/20896355/233043010-fc897fa4-7695-4a22-81bf-b390e2e73190.png)
![WX20230419-180514@2x](https://user-images.githubusercontent.com/20896355/233043029-bf21024c-0601-430c-af19-d86d81aeaa29.png)

JdkSslContext 如下
SSLContext context = SSLContext.getInstance("TLCPv1.1");
![jdksslcontext](https://user-images.githubusercontent.com/20896355/233043709-cf7a5127-0f13-40fe-ac66-b99cbb45e218.png)

麻烦大佬帮忙看看

**Comment by johnshajiang** [comment]
若使用Oracle JDK的话，它需要验证JCE Provider的签名。该签名所使用的私钥对应的证书（公钥）必须要由Oracle JCE Coding CA颁发。
所以，当使用TencentKonaSMSuite的源代码进行构建（包括执行其中的单元测试）时，请使用OpenJDK。

我平时在开发时也只是使用OpenJDK。不过，在正式发布制品（.jar）到Maven仓库时，会对.jar文件进行签名。
