### ISSUE TITLE
是否支持GMSSLv1.1 协议？

### ISSUE THREAD

**Issue by zhaodaye2022** [Tencent/TencentKonaSMSuite#204]

**Comment by johnshajiang** [comment]
支持的。
在我们这里，该协议的名称为TLCPv1.1。因为国标GB/T 38636-2020的全称为Transport layer cryptography protocol。

**Comment by johnshajiang** [comment]
@zhaodaye2022 
下面链接中有一些集成到第三方组件（如Netty，Jetty），的示例。
https://github.com/Tencent/TencentKonaSMSuite/tree/master/kona-ssl/src/test/java/com/tencent/kona/ssl/demo

**Comment by johnshajiang** [comment]
@zhaodaye2022 
请问，你是否已经试用过TKSS的GMSSL/TLCP特性了？
如果能够正常使用的话，请关闭该issue。
如果有问题，欢迎随时提出来。
