### ISSUE TITLE
为什么加密套件不支持TLS_ECC_SM4_GCM_SM3?

### ISSUE THREAD

**Issue by solio** [Tencent/TencentKonaSMSuite#237]
https://github.com/Tencent/TencentKonaSMSuite/blob/b62d06e7334a542c66c1a891df3f9819eeb54734/kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/CipherSuite.java#LL68C52-L68C67

这里加密套件仅支持TLCP_ECC_SM4_GCM_SM3，协议应该不影响加密套件吧，这里不支持的TLS话对我们来说比较难受

**Comment by johnshajiang** [comment]
TLCP国标定义的是`ECC_SM4_GCM_SM3(0xE053)`，尚没有RFC规范将国密密码套件引入TLS 1.2协议。
不过，我们支持了[RFC 8998]，可以在TLS 1.3协议中使用国密密码套件`TLS_SM4_GCM_SM3(0x00C6)`。

[RFC 8998]:
<https://www.rfc-editor.org/rfc/rfc8998.html>

**Comment by johnshajiang** [comment]
@solio 
如果您了解到有其它方的实现在TLS 1.2中支持了`ECC_SM4_GCM_SM3`，请让我们知晓。我们可以去参考一下。

我们目前认为，如果没有相关RFC标准支持的话，可能无法保证各个实现之间的交互性。首先，该密码套件的ID就是一个未知数。直接使用TLCP定义的`0xE053`也未必合适。毕竟，RFC和国标分配的ID不太可能一致。

而且，还要考虑到，这样的一个密码套件的内涵到底是什么？
比如，它应该是`TLS_ECDH_SM2_WITH_SM4_GCM_SM3`，或是`TLS_ECDH_ECDSA_WITH_SM4_GCM_SM3`？
前者的签名算法为SM2；后者的签名算法为ECDSA，但可以使用SM2椭圆曲线。

再扩展一下，是否需要在TLS 1.2中支持`ECDHE_SM4_GCM_SM3`呢？
这样的密码套件的内涵是什么呢？
它应该是`TLS_SM2_WITH_SM4_GCM_SM3`，`TLS_ECDHE_SM2_WITH_SM4_GCM_SM3`，或是`TLS_ECDHE_ECDSA_WITH_SM4_GCM_SM3`？
此处，`SM2`和`ECDHE`是两个不同的密钥交换算法。

总之，一些细节需要有标准化文件去厘清。

如果您有更多的信息或想法，欢迎分享。

**Comment by solio** [comment]
@johnshajiang 没有疑虑，按照标准来是对的。我们只是用了一些非标的国密客户端。
