### ISSUE TITLE
SharedSecretsUtil.netInetAddressGetOriginalHostName可能很慢

### ISSUE THREAD

**Issue by wsc12** [Tencent/TencentKonaSMSuite#245]
1.  今天我使用了贵公司开发的GMSSL功能，发现这里耗时很长，debug没有发现问题，后面通过把源码下载下来编译再debug发现在这里出现了耗时大的问题
2. 第一次耗时10多秒，第二次耗时30多秒，但是不管是10多秒还是30多秒，我们都无法接受，所以我就直接通过修改部分代码进行测试

add: 
```
private static final boolean queryHostName
        = Boolean.parseBoolean(System.getProperty("kona.sslsocket.queryHostName","true"));
```
modify:
```
       String originalHostname = null;
        if(queryHostName){
            // TODO 这个有时候获取的时候长有时候短
            originalHostname = SharedSecretsUtil.netInetAddressGetOriginalHostName(
                inetAddress);
        }else{
            // 这个直接获取
            originalHostname = inetAddress.getHostAddress();
        }
```
3. 修改后的建立连接只花费了 500多毫秒  ,  这样我们就能通过在java后添加参数控制了
4. 由于可能是我们公司的网关的问题，不过我觉得这里最好还是改一下，一般我们大公司的网关都是绕来绕去的

**Comment by johnshajiang** [comment]
请将系统属性`com.tencent.misc.useSharedSecrets`设置为`true`再试试。

**Comment by johnshajiang** [comment]
> 请将系统属性`com.tencent.misc.useSharedSecrets`设置为`true`再试试。

@wsc12 
请问您是否上面的系统属性？它是否会改善性能？
另外，您使用的JDK版本是什么？

**Comment by wsc12** [comment]
嗯嗯，添加参数是有用的，没有添加之前需要耗时 9s - 30s , 添加后耗时 0.6s 左右，JDK1.8 - JDK11 都是生效的

System.setProperty("com.tencent.misc.useSharedSecrets","true");










在 2023-05-31 10:13:14，"John Jiang" ***@***.***> 写道：

请将系统属性com.tencent.misc.useSharedSecrets设置为true再试试。

@wsc12
请问您是否上面的系统属性？它是否会改善性能？
另外，您使用的JDK版本是什么？

**Comment by johnshajiang** [comment]
那么仅使用这个属性`com.tencent.misc.useSharedSecrets`是否就可以满足你们的需求了？

**Comment by wsc12** [comment]
目前写Demo就只碰到这个问题，没有发现什么其他的问题







在 2023-06-02 10:46:39，"John Jiang" ***@***.***> 写道：

那么仅使用这个属性com.tencent.misc.useSharedSecrets是否就可以满足你们的需求了？

**Comment by johnshajiang** [comment]
明白，我刚才的意思是说，使用那个系统属性之后是否就能解决这个问题了。
如果这个问题已经解决的话，烦请关闭这个issue。
如果未来遇到其它问题，可以开新的issue。

**Comment by wsc12** [comment]
好的，我去关闭下













在 2023-06-02 10:53:05，"John Jiang" ***@***.***> 写道：

明白，我刚才的意思是说，使用那个系统属性之后是否就能解决这个问题了。
如果这个问题已经解决的话，烦请关闭这个issue。
如果未来遇到其它问题，可以开新的issue。

**Comment by wsc12** [comment]
问题已经解决：将属性 com.tencent.misc.useSharedSecrets设置为true

**Comment by johnshajiang** [comment]
@wsc12 
又考虑了一下，也许可以在JDK 8默认启用`SharedSecrets`，请见#252。

如果您有其它建议，欢迎讨论。

**Comment by johnshajiang** [comment]
@wsc12 
Just FYI
刚才解决了#252，并且发布了1.0.9-SNAPSHOT版本。
可以使用这个版本进行测试。
