### ISSUE TITLE
Add TLS demo for Tomcat

### ISSUE THREAD

**Issue by johnshajiang** [Tencent/TencentKonaSMSuite#328]
It would add a demo on integrating KonaSSL to Tomcat server on TLS.

**Comment by xudong-1990** [comment]
May I ask when the tomcat demo can be completed?

**Comment by johnshajiang** [comment]
Just looked through some Tomcat embedded server examples on TLS.
It looked Tomcat doesn't provider handy APIs for using custom SSLContext.

**Comment by johnshajiang** [comment]
[TLSWithTomcatDemo] expands some Tomcat classes to take Kona-family providers to work, though this solution is tricky and not simple.

[TLSWithTomcatDemo]:
<https://github.com/Tencent/TencentKonaSMSuite/blob/master/kona-ssl/src/test/java/com/tencent/kona/ssl/demo/TLSWithTomcatDemo.java>

**Comment by shenxuebing** [comment]
如何在不改造代码的情况下，只配置tomcat的server.xml实现呢？这种方式似乎需要加载一个自定义jar，从而实现

**Comment by johnshajiang** [comment]
目前只是实现/扩展了Tomcat的接口/类，并没有直接修改Tomcat的源代码，那么理论上，也许可以将这些类应用到独立的Tomcat Server中。
为了方便地复用这些定制实现类，可以将它们放入一个独立的jar文件中。
这些设计与实现上的细节问题，还需要应用方根据自身的需求和场景去推敲。
