### ISSUE TITLE
用腾讯KonaCrypto国密SM2套件的时候，无法解密JS加密的SM2

### ISSUE THREAD

**Issue by zgx666** [Tencent/TencentKonaSMSuite#363]
用腾讯KonaCrypto国密套件的时候，用套件生成的公钥和私钥进行SM2加解密正常，但是在使用小程序的wechat-miniprogram/sm-crypto，GITHUB地址：https://github.com/antherd/sm-crypto 里面的SM2加密内容，无法在KonaCrypto的SM2中进行解密，公钥和私钥都是同一对，不知道其他人是否有遇到过这个问题？

**Comment by johnshajiang** [comment]
需要了解微信小程序sm-crypto组件生成的SM2密文的格式。
KonaSMSuite/KonaCrypto要求的SM2密文格式为`DER C1C3C2`。

另外，我们提供了一个工具[SM2Ciphertext]，可以在四种格式之间进行转换。
请参考SM2WithBCTest中的[用法]。

[SM2Ciphertext]:
<https://github.com/Tencent/TencentKonaSMSuite/blob/master/kona-crypto/src/main/java/com/tencent/kona/crypto/util/SM2Ciphertext.java>

[用法]:
<https://github.com/Tencent/TencentKonaSMSuite/blob/master/kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2WithBCTest.java#L88>

**Comment by johnshajiang** [comment]
@zgx666 
项目[sm-crypto]有如下表述，
```
// cipherMode 1 - C1C3C2，0 - C1C2C3，默认为1
String encryptData = Sm2.doEncrypt(msg, publicKey); // 加密结果
String decryptData = Sm2.doDecrypt(encryptData, privateKey); // 解密结果
```
看起来，它默认使用的密文格式为`C1C3C2`，但这个格式可能没有使用`ASN.1`编码，即，不是Kona国密套件使用的`DER C1C3C2`。
你需要先确认一下这个问题。

[sm-crypto]:
<https://github.com/antherd/sm-crypto>

**Comment by zgx666** [comment]
我看了下,wechat-miniprogram/sm-crypto应该也是用ASN.1编码,现在的情况是用KonaCrypto套件生成的SM2密钥,可以在wechat-miniprogram/sm-crypto里面加密解密,wechat-miniprogram/sm-crypto的密钥也可以在KonaCrypto里面加密解密,但是如果用KonaCrypto套件加密后的内容,无法在wechat-miniprogram/sm-crypto里面进行解密,同理wechat-miniprogram/sm-crypto加密的内容无法在KonaCrypto里面解密.应该和密钥无关

**Comment by zgx666** [comment]
@johnshajiang 会是加解密里面的算法不同么

**Comment by zgx666** [comment]
@johnshajiang 
下面是腾讯KonaCrypto的代码
public static void main(String[] args) throws Exception {
    Security.addProvider(new KonaCryptoProvider());
    byte[] encodedPublicKey =hexStringToBytes("04DBD8D3FD7844801814E25DE6DFD08FC8BCA83EFA048C9C079CAE42BA3B9C355E68B73CF433D00778550E77C1C88D3075DB93098AC4EA6F0CB294AB761BE3133B");
    byte[] encodedPrivateKey=hexStringToBytes("AACE7D9B2CC5BA0F852AEA190C41DE48776CFCCD90609426BA561493B91465B4");
    KeyFactory keyFactory = KeyFactory.getInstance("SM2");
    SM2PublicKeySpec publicKeySpec = new SM2PublicKeySpec(encodedPublicKey);
    PublicKey publicKey = keyFactory.generatePublic(publicKeySpec);
    SM2PrivateKeySpec privateKeySpec = new SM2PrivateKeySpec(encodedPrivateKey);
    PrivateKey privateKey = keyFactory.generatePrivate(privateKeySpec);
    Cipher cipher = Cipher.getInstance("SM2");
    cipher.init(Cipher.ENCRYPT_MODE, publicKey);
    String testciphertext="fb07531cb47932136dee51a4d307f5f7";
    byte[] ciphertext= cipher.doFinal((testciphertext).getBytes());
    String ciphertextStr=new String(ciphertext);
    System.out.println("加密结果输出"+ciphertextStr);
    String ciphertextHex=getHexString(ciphertext,false);
    System.out.println("转十六进制加密结果输出"+ciphertextHex);
   cipher.init(Cipher.DECRYPT_MODE, privateKey);
    byte[] cleartext = cipher.doFinal(ciphertext);
    String cleartextStr=new String(cleartext);
    System.out.println("解密输出"+cleartextStr);
    String cleartextHex=getHexString(cleartext,true);
    System.out.println("转十六进制解密输出"+cleartextHex);
    //下面用JS加密的内容拿过来解密失败
   byte[] ciphertextByJs =hexStringToBytes("0ba3a07a74bd07087756da25aab398987bfdb41aee250ba492b949a7749f797035fa7083ae00c4dc340be66f5356e295075416d5b3814207d34f2e1518447bef8eab9a551078f8e59bf4b576e8b03b71c20ca37eafa17338a6756841124e283136679e9787ef659e83adfbb555aaab9f62484fb4897ffbba1185483f216dc72a");
    byte[] cleartextJs = cipher.doFinal(ciphertextByJs);
     cleartextStr=new String(cleartextJs);
    System.out.println("js版本解密输出"+cleartextStr);
     cleartextHex=getHexString(cleartextJs,true);
    System.out.println("js版本转十六进制解密输出"+cleartextHex);

}


下面是JS版本代码
public static void main(String[] args) {
    String privateKey = "AACE7D9B2CC5BA0F852AEA190C41DE48776CFCCD90609426BA561493B91465B4"; // 公钥
    String publicKey ="04DBD8D3FD7844801814E25DE6DFD08FC8BCA83EFA048C9C079CAE42BA3B9C355E68B73CF433D00778550E77C1C88D3075DB93098AC4EA6F0CB294AB761BE3133B"; // 私钥
    System.out.println("私钥"+privateKey);
    System.out.println("公钥"+publicKey);
    String msg="fb07531cb47932136dee51a4d307f5f7";
    // cipherMode 1 - C1C3C2，0 - C1C2C3，默认为1
    String encryptData = Sm2.doEncrypt(msg, publicKey); // 加密结果
    //加密结果fb9d3515483ce49eb6fd3c18a4e8492ba382176f9661f334b87ff99214a09d827ba145deb26a935ed4072fc05d679ac029439f84605f34d9e27686d
    // 60d73cfabf5ab3a9aa79912bc9b6a07222f166786194fb0c1cae634b65c9381615a2c9f55ac3297497e36214efee4803b5f74e620432c367fdda295b704fd03a1615f73e6
    System.out.println("加密结果"+encryptData);
    String decryptData = Sm2.doDecrypt(encryptData, privateKey); // 解密结果
    //解密结果fb07531cb47932136dee51a4d307f5f7
    System.out.println("解密结果"+decryptData);
}

**Comment by johnshajiang** [comment]
@zgx666 
KonaCrypto代码中的由sm-crypto生成密文看起来没有经过ASN.1编码，
```
0ba3a07a74bd07087756da25aab398987bfdb41aee250ba492b949a7749f797035fa7083ae00c4dc340be66f5356e295075416d5b3814207d34f2e1518447bef8eab9a551078f8e59bf4b576e8b03b71c20ca37eafa17338a6756841124e283136679e9787ef659e83adfbb555aaab9f62484fb4897ffbba1185483f216dc72a
```

你应该可以看到，由KonaCrypto生成的SM2密文的HEX会像下面这样，
```
3081880220513bc8c801c2536e6fcab079bf08880d8ef238fdf6368330a74de57e198a059802205e145c03626c122048e3c6e84ac84feb24e11e05e1d33275f1d567c0d08d333a042099d8d55c2177ea61e4295917d3826f6a05205dccd22817d7a4dc3cf318dd7e5c042070ada8ecff31216a4828dd3f2ff956754ae0c68b3f2d1d23052a2a2de48a0d95
```

**Comment by zgx666** [comment]
@johnshajiang 
私钥AACE7D9B2CC5BA0F852AEA190C41DE48776CFCCD90609426BA561493B91465B4
公钥04DBD8D3FD7844801814E25DE6DFD08FC8BCA83EFA048C9C079CAE42BA3B9C355E68B73CF433D00778550E77C1C88D3075DB93098AC4EA6F0CB294AB761BE3133B
经过JS版本的加密8a350777374e09d6bf121549e416efee64032c36e13e75e3506ea723e15ed2b57e91cf82021f94f9d8196c1c446cf228247a2c890ff2762703addd285bf73321d379701a0b05711807fbad45578c9adb854a3d14365dc087c1c70e2c1d0cb028b6eb4ddfad17dfd8ea9bd4986d1084df466f84c3e2a52a8af957c4b823c6f79c

String js="8a350777374e09d6bf121549e416efee64032c36e13e75e3506ea723e15ed2b57e91cf82021f94f9d8196c1c446cf228247a2c890ff2762703addd285bf73321d379701a0b05711807fbad45578c9adb854a3d14365dc087c1c70e2c1d0cb028b6eb4ddfad17dfd8ea9bd4986d1084df466f84c3e2a52a8af957c4b823c6f79c";

        byte[] ciphertextBC =hexStringToBytes(js);
        byte[] derC1C3C2 = SM2Ciphertext.builder()
                .format(SM2Ciphertext.Format.RAW_C1C3C2)
                .encodedCiphertext(ciphertextBC)
                .build()
                .derC1C3C2();
        cipher.init(Cipher.DECRYPT_MODE, privateKey);
        byte[] cleartext = cipher.doFinal(derC1C3C2)；
在这解密的时候，我尝试过各种编码格式组合，似乎都会报错
       //format     build
       // DER_C1C3C2 rawC1C3C2    Invalid lenByte
        //DER_C1C3C2 rawC1C2C3    Invalid lenByte
        //DER_C1C3C2 derC1C2C3    Invalid lenByte
        //RAW_C1C3C2 derC1C2C3     The peer public point is invalid
        //RAW_C1C3C2 derC1C3C2     The peer public point is invalid
        //RAW_C1C3C2 rawC1C2C3     Decode SM2 ciphertext failed
        //DER_C1C2C3 rawC1C2C3     Invalid lenByte
        //DER_C1C2C3 rawC1C3C2     Invalid lenByte
        //DER_C1C2C3 derC1C3C2     Invalid lenByte
        //RAW_C1C2C3 derC1C3C2     The peer public point is invalid
        //RAW_C1C2C3 derC1C2C3     The peer public point is invalid
        //RAW_C1C2C3 derC1C2C3     Decode SM2 ciphertext failed

**Comment by kejiancai** [comment]
公钥私钥对应该是匹配的，针对如上提供的公私钥，在https://const.net.cn/tool/sm2/genkey/该网站通过私钥是可以生成出同样的公钥，细微差别前面多了04，我也尝试了wechat-miniprogram/sm-crypto里面的加解密，通过同样的密钥对分别在各自的项目中加解密是正常，分别拿到另一个项目中加解密就出错，怀疑是加解密的规格不同

**Comment by zgx666** [comment]
@johnshajiang 这边通过JS版本的加密,在在线解密网站https://the-x.cn/zh-cn/cryptography/Sm2.aspx  这个可以正常解密,插件提醒符合RFC4648 BaseN编码规则.不过加密的这串,在Kona Crypto进行解密的时候.我通过SM2Ciphertext工具转换,尝试了各个组合,报了下面的异常.
 public static void main(String[] args) throws Exception{
        Security.addProvider(new KonaCryptoProvider());
        //------------------------------------JS加密版本--------------------------------------------
        String publickeyJs="04f99c74336238773f687ed7e1b86a6d3161f59c366eb180b508e56202370db33790b578f9fad1c231778e500bb815f7911934cc2533c45ffaad54e3cd76cbdc49";
        String privateKeyJs="e47f777da737a9ab68fb9d058fcc66a386220061e969cbd8442ae5784887b710";
        //加密的内容
        String msg="fb07531cb47932136dee51a4d307f5f7";
        //JS加密版本
        String encryptData = Sm2.doEncrypt(msg, publickeyJs); // 加密结果
        //加密结果3779bbd2ace086b136be626d5363684fb81912e66b23afbe7e2b3f5d3314642e566498f22e840224f3eddefa543b0fb787434f4d1bd4faf82825065f79282d5b2a465313860066ecf9e960a12472ff1f83ba9fd9e2bd835256fc2158104fe8faf0dbdb5b698fb5b4c458175a6c64b4870dec048810cad87241fbea5c0e4fda9e
        System.out.println("通过JS加密的结果"+encryptData);
        byte[] ciphertextBC =hexStringToBytes(encryptData);
        //js版本的解密
        String decryptData = Sm2.doDecrypt(getHexString(ciphertextBC,false), privateKeyJs); // 解密结果
        //解密结果fb07531cb47932136dee51a4d307f5f7
        System.out.println("解密结果"+decryptData);

        //-------------------------------Kona Crypto解密--------------------------------------------
        byte[] encodedPublicKey =hexStringToBytes(publickeyJs);
        byte[] encodedPrivateKey=hexStringToBytes(privateKeyJs);
        KeyFactory keyFactory = KeyFactory.getInstance("SM2");
        SM2PublicKeySpec publicKeySpec = new SM2PublicKeySpec(encodedPublicKey);
        PublicKey publicKey = keyFactory.generatePublic(publicKeySpec);
        SM2PrivateKeySpec privateKeySpec = new SM2PrivateKeySpec(encodedPrivateKey);
        PrivateKey privateKey = keyFactory.generatePrivate(privateKeySpec);
        Cipher cipher = Cipher.getInstance("SM2");
        //format     build
        //RAW_C1C3C2 derC1C3C2  The peer public point is invalid
        //RAW_C1C3C2 derC1C2C3  The peer public point is invalid
        //RAW_C1C3C2 derC1C2C3  Decode SM2 ciphertext failed
        //DER_C1C3C2 rawC1C2C3  Invalid lenByte
        //DER_C1C3C2 rawC1C3C2  Invalid lenByte
        //DER_C1C3C2 derC1C2C3  Invalid lenByte
        //RAW_C1C2C3 derC1C2C3  The peer public point is invalid
        //RAW_C1C2C3 derC1C3C2  The peer public point is invalid
        //RAW_C1C2C3 rawC1C3C2  Decode SM2 ciphertext failed
        //DER_C1C2C3 derC1C3C2  Invalid lenByte
        //DER_C1C2C3 rawC1C3C2  Invalid lenByte
        //DER_C1C2C3 rawC1C2C3  Invalid lenByte
        byte[] derC1C3C2 = SM2Ciphertext.builder()
                .format(SM2Ciphertext.Format.DER_C1C2C3)
                .encodedCiphertext(ciphertextBC)
                .build()
                .rawC1C2C3();
        cipher.init(Cipher.DECRYPT_MODE, privateKey);
        byte[] cleartext = cipher.doFinal(derC1C3C2);
        System.out.println("解密内容结果"+getHexString(derC1C3C2,false));
        System.out.println("解密结果"+getHexString(cleartext,false));
    }

**Comment by johnshajiang** [comment]
@zgx666 
> 这边通过JS版本的加密,在在线解密网站https://the-x.cn/zh-cn/cryptography/Sm2.aspx 这个可以正常解密,插件提醒符合RFC4648 BaseN编码规则

能否清晰地表述你的测试？
在如下页面中，你的输入分别是什么？
https://the-x.cn/zh-cn/cryptography/Sm2.aspx 

我的如下输入正确吗？其中，私钥是`AACE7D9B2CC5BA0F852AEA190C41DE48776CFCCD90609426BA561493B91465B4`，该工具自动将它转换成了PKCS#8私钥格式。
<img width="944" src="https://github.com/Tencent/TencentKonaSMSuite/assets/20450620/48f76e9a-84f5-48d5-99c5-7586b0e8cdb1">

但点击`SM2私钥解密`按钮之后，报密文错误，如下所示，
<img width="430" src="https://github.com/Tencent/TencentKonaSMSuite/assets/20450620/c54b1099-43cb-4ef9-8382-b2f14a5e339e">

**Comment by johnshajiang** [comment]
@kejiancai 
> 公钥私钥对应该是匹配的

我只是说，作了格式转换之后，新生成的密文中的公钥与程序中的私钥不匹配。

> 针对如上提供的公私钥，在https://const.net.cn/tool/sm2/genkey/ 该网站通过私钥是可以生成出同样的公钥，细微差别前面多了04，我也尝试了wechat-miniprogram/sm-crypto里面的加解密，通过同样的密钥对分别在各自的项目中加解密是正常，分别拿到另一个项目中加解密就出错，怀疑是加解密的规格不同

我们有与BouncyCastle的[交互测试]，而且与铜锁(Tongsuo)也能成功地进行交互。
我现在只能确定TencentKonaSMSuite中的密文格式，但无法确认sm-crypto的SM2加密细节。
是否也应该请它的开发者帮忙看看这个问题？

[交互测试]:
<https://github.com/Tencent/TencentKonaSMSuite/blob/master/kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2WithBCTest.java#L72>

**Comment by zgx666** [comment]
> 3779bbd2ace086b136be626d5363684fb81912e66b23afbe7e2b3f5d3314642e566498f22e840224f3eddefa543b0fb787434f4d1bd4faf82825065f79282d5b2a465313860066ecf9e960a12472ff1f83ba9fd9e2bd835256fc2158104fe8faf0dbdb5b698fb5b4c458175a6c64b4870dec048810cad87241fbea5c0e4fda9e

**Comment by zgx666** [comment]
@johnshajiang 
在如下页面中
https://the-x.cn/zh-cn/cryptography/Sm2.aspx
输出私钥e47f777da737a9ab68fb9d058fcc66a386220061e969cbd8442ae5784887b710
加密结果3779bbd2ace086b136be626d5363684fb81912e66b23afbe7e2b3f5d3314642e566498f22e840224f3eddefa543b0fb787434f4d1bd4faf82825065f79282d5b2a465313860066ecf9e960a12472ff1f83ba9fd9e2bd835256fc2158104fe8faf0dbdb5b698fb5b4c458175a6c64b4870dec048810cad87241fbea5c0e4fda9e
SM2解密得出
fb07531cb47932136dee51a4d307f5f7
![image](https://github.com/Tencent/TencentKonaSMSuite/assets/37567225/ef9d55f8-b535-44d0-9aef-456a246e7cd3)

可以以我上面发的最新测试代码里面的公钥私钥进行测试
公钥04f99c74336238773f687ed7e1b86a6d3161f59c366eb180b508e56202370db33790b578f9fad1c231778e500bb815f7911934cc2533c45ffaad54e3cd76cbdc49
私钥e47f777da737a9ab68fb9d058fcc66a386220061e969cbd8442ae5784887b710
加密结果
3779bbd2ace086b136be626d5363684fb81912e66b23afbe7e2b3f5d3314642e566498f22e840224f3eddefa543b0fb787434f4d1bd4faf82825065f79282d5b2a465313860066ecf9e960a12472ff1f83ba9fd9e2bd835256fc2158104fe8faf0dbdb5b698fb5b4c458175a6c64b4870dec048810cad87241fbea5c0e4fda9e
解密结果
fb07531cb47932136dee51a4d307f5f7

**Comment by johnshajiang** [comment]
哈，原来就是密文的起始处少了一个`04`，它表示该公钥坐标的格式为`uncompressed`。`SM2Ciphertext`认为这个标志位是不可少的。

**Comment by johnshajiang** [comment]
刚才查看了SM2加密算法的国标`GB/T 32918.4-2016`，其中给出的密文示例均以`04`开头。
另外，BouncyCastle生成的密文格式虽然也没有使用ASN.1编码，但它的`C1`部分也以`04`开头。

**Comment by johnshajiang** [comment]
其实，微信小程序[sm-crypto]的文档中有如下一提示，
> ps：密文会在解密时自动追加 04，如遇到其他工具追加的 04 需手动去除再传入。

[sm-crypto]:
<https://github.com/wechat-miniprogram/sm-crypto>

**Comment by zgx666** [comment]
@johnshajiang 早上试了下，确实是因为JS半的密文没有加04，导致在KonaCrypto里面转BC后解密失败。  
 byte[] derC1C3C2 = SM2Ciphertext.builder()
                .format(SM2Ciphertext.Format.RAW_C1C3C2)
                .encodedCiphertext(ciphertextByWZ)
                .build()
                .derC1C3C2();
  将JS版本的密文加上04后，解密正常。此问题已结，太感谢了
