### ISSUE TITLE
请教一下，为什么很短的数据也需要分包？

### ISSUE THREAD

**Issue by tang-world** [Tencent/TencentKonaSMSuite#370]
涉及到的代码如下图
![image](https://github.com/Tencent/TencentKonaSMSuite/assets/46295500/8ff2d6ab-4e71-4580-9ce5-acadc644a63e)

我的理解的代码的大致意思是：当同一个ssl链接上的第二次数据交互开始，数据的第一个字节会被单独加密传输过去，如果是很短的原文传输，比如10个字节，那么为何第一个字节要单独分一个包传过去呢？

下面是一些其他额外可能有用的信息：
我使用的协议 gmssl，即tlcp1.1，协议版本号为0x0101，加密的算法使用cbc模式
JDK：corretto-11.0.20.1  KonaSmSuite maven版本：1.0.9  操作系统平台：win11

**Comment by johnshajiang** [comment]
对于TLCP协议应该不需要这个处理。
我刚才修改了程序，已经发布到了Maven Snapshots仓库（不是Maven Central仓库）中，版本号为`1.0.10-SNAPSHOT`，请帮忙测试。
制品地址：https://oss.sonatype.org/content/repositories/snapshots/com/tencent/kona/

**Comment by tang-world** [comment]
收到，测试通过了，没有走分包的逻辑了，感谢~

**Comment by johnshajiang** [comment]
非常感谢你的测试与确认。
我晚点儿会将修复补丁发布GitHub上。

**Comment by johnshajiang** [comment]
#371 已经解决了这个问题。
