### ISSUE TITLE
请问有没有支持 openharmony 系统的计划？？

### ISSUE THREAD

**Issue by JackyKeke** [Tencent/TencentKonaSMSuite#387]
请问有没有支持 openharmony 系统的计划？？
Is there any plan to support openharmony system?

**Comment by johnshajiang** [comment]
@JackyKeke 
非常感谢能够关注到TencentKonaSMSuite！

本项目是纯Java实现，而OpenHarmony似乎并不支持该语言，虽然HarmonyOS支持（?）
所以，你能否给出支持OpenHarmony的具体要求，或者给出一些参考和指引？

**Comment by JackyKeke** [comment]
之前制作国密sslvpn的Android产品，是使用贵团队Kona国密套件作中间件的。
现在需要制作国密sslvpn的鸿蒙产品，希望贵团队能根据需要制作相应的鸿蒙中间件。
据我了解 openharmony 的底层思路跟 typescript 差不多 ，但是呢鸿蒙那边的加解密密码通用库我也不是很清楚怎么跟 java 的对应起来。 
市面上在 ts 做国密sslvpn的产品也几乎几乎没有，希望你们能给点思路

**Comment by johnshajiang** [comment]
那么，你们是否考虑使用C语言的国密实现呢？
你们应该已经了解过铜锁/Tongsuo。

**Comment by JackyKeke** [comment]
还没了解 我看看
我先关了 issue
