### ISSUE TITLE
kona-demo运行访问报错

### ISSUE THREAD

**Issue by weijunlu** [Tencent/TencentKonaSMSuite#476]
1. 搭建个springboot web服务， pom.xml文件中引入kona国密套件4个组件， 版本为1.0.9
        <dependency>
            <groupId>com.tencent.kona</groupId>
            <artifactId>kona-crypto</artifactId>
            <version>1.0.9</version>
        </dependency>
    别的组件就不一一列出来了    

2. 使用kona-demo模块中的JettyServer例子
3. idea中启动服务，然后通过浏览器访问https://localhost:8443/jetty， 报错信息如下：
```
com.tencent.kona.ssl|SEVERE|31|qtp2113243119-19|2023-10-19 14:33:51.331 CST|TransportContext.java:370|Fatal (DECODE_ERROR): Received fatal alert: decode_error (
"throwable" : {
  javax.net.ssl.SSLHandshakeException: Received fatal alert: decode_error
  	at com.tencent.kona.sun.security.ssl.Alert.createSSLException(Alert.java:131)
  	at com.tencent.kona.sun.security.ssl.Alert.createSSLException(Alert.java:117)
  	at com.tencent.kona.sun.security.ssl.TransportContext.fatal(TransportContext.java:365)
  	at com.tencent.kona.sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
  	at com.tencent.kona.sun.security.ssl.TransportContext.dispatch(TransportContext.java:204)
  	at com.tencent.kona.sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
  	at com.tencent.kona.sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:736)
  	at com.tencent.kona.sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:691)
  	at com.tencent.kona.sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:505)
  	at com.tencent.kona.sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:481)
  	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:626)
  	at org.eclipse.jetty.io.ssl.SslConnection.unwrap(SslConnection.java:429)
  	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:718)
  	at org.eclipse.jetty.server.HttpConnection.fillRequestBuffer(HttpConnection.java:350)
  	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
  	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
  	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
  	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555)
  	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410)
  	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164)
  	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
  	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
  	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
  	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
  	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
  	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
  	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
  	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
  	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
  	at java.lang.Thread.run(Thread.java:750)}
```
4. 然后怀疑kona-demo中带的keystore.p12和truststore.p12有问题，就自己生成一个，生成方式如下：
```
java -cp * com.tencent.kona.pkix.tool.KeyTool -genkeypair -keystore ca.ks -storetype PKCS12 -storepass testpasswd -keyalg EC -groupname curveSM2 -sigalg SM3withSM2 -dname CN=ca -alias ca
java -cp * com.tencent.kona.pkix.tool.KeyTool -genkeypair -keystore ee.ks -storetype PKCS12 -storepass testpasswd -keyalg EC -groupname curveSM2 -sigalg SM3withSM2 -dname CN=ee -alias ee
java -cp * com.tencent.kona.pkix.tool.KeyTool -certreq -keystore ee.ks -storetype PKCS12 -storepass testpasswd -alias ee -file ee.csr
java -cp * com.tencent.kona.pkix.tool.KeyTool -gencert -rfc -keystore ca.ks -storetype PKCS12 -storepass testpasswd -sigalg SM3withSM2 -alias ca -infile ee.csr -outfile ee.crt
java -cp * com.tencent.kona.pkix.tool.KeyStoreTool -type PKCS12 -alias trust1,trust2 -certs ee.crt -store store.p12 -storePasswd testpasswd
```
<img width="565" alt="1697697839008" src="https://github.com/Tencent/TencentKonaSMSuite/assets/104422448/edf29cff-a4bc-48a3-b456-bef1134c5f8d">

然后application.yml中修改如下：
```
trust-store-provider: Kona
trust-store-type: PKCS12
trust-store: classpath:ssl/ee.crt
trust-store-password: testpasswd

key-store-provider: Kona
key-store-type: PKCS12
key-store: classpath:ssl/ca.ks
key-store-password: testpasswd
```
重新编译，然后启动服务，再访问`https://localhost:8443/jetty`，报错和上面一样。

**Comment by weijunlu** [comment]
完整报错日志如下：
[error_log.txt](https://github.com/Tencent/TencentKonaSMSuite/files/13039048/error_log.txt)

**Comment by johnshajiang** [comment]
@weijunlu 
你用的浏览器可能不支持国密算法吧？
我猜想它不能验证下面的签名。

```
"CertificateVerify": {
  "signature algorithm": sm2sig_sm3
  "signature": {
    0000: 30 45 02 21 00 D2 63 E6   BF D2 14 6E EC 9D 58 F1  0E.!..c....n..X.
    0010: D5 23 78 85 E3 D4 EC 47   DB AC B1 10 1F 0B 1C E2  .#x....G........
    0020: 9A A6 FE 45 D6 02 20 08   D6 33 1F 7B D8 88 3E 93  ...E.. ..3....>.
    0030: 53 18 E6 A7 B1 14 93 E2   68 55 41 D0 E7 55 A4 29  S.......hUA..U.)
    0040: 61 54 0B C1 8B BF 3D                               aT....=
  }
}
```

**Comment by weijunlu** [comment]
@johnshajiang 多谢帮忙看问题哈，开始用的是chrom浏览器，也怀疑是浏览器问题。下了360安全浏览器，重新试了下。日志看不出来报错，但浏览器页面没有内容返回。
<img width="959" alt="1697719742524" src="https://github.com/Tencent/TencentKonaSMSuite/assets/104422448/9693b460-d769-47c9-a443-3e757f727136">
对应日志如下：
[360brows-log.txt](https://github.com/Tencent/TencentKonaSMSuite/files/13042766/360brows-log.txt)

**Comment by weijunlu** [comment]
Java 版本如下：
$ java -version
java version "1.8.0_341"
Java(TM) SE Runtime Environment (build 1.8.0_341-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.341-b10, mixed mode)

**Comment by johnshajiang** [comment]
浏览器返回了`Finished`消息，握手应该是成功了。
```
com.tencent.kona.ssl|FINE|B1|qtp898695324-27|2023-10-19 20:41:29.684 CST|Finished.java:1044|Consuming client Finished handshake message (
"Finished": {
  "verify data": {
    0000: 84 60 32 D3 2E E6 D4 CC   53 53 51 AE 27 EC 53 63  .`2.....SSQ.'.Sc
    0010: 05 8A 25 BF E8 0D DB 72   08 6C 33 A4 47 0C CA 5F  ..%....r.l3.G.._
    0020: 3A 1B DA 9D E2 9D EB 59   FD 1D BB E3 42 06 6E 87  :......Y....B.n.
  }'}
)
```

可能是后面的HTTP应用层出了问题。
```
com.tencent.kona.ssl|FINE|B1|qtp898695324-27|2023-10-19 20:41:29.687 CST|SSLCipher.java:2071|Plaintext before ENCRYPTION (
  0000: 48 54 54 50 2F 31 2E 31   20 34 32 36 20 55 70 67  HTTP/1.1 426 Upg
  0010: 72 61 64 65 20 52 65 71   75 69 72 65 64 0D 0A 43  rade Required..C
  0020: 6F 6E 74 65 6E 74 2D 54   79 70 65 3A 20 74 65 78  ontent-Type: tex
  0030: 74 2F 68 74 6D 6C 3B 63   68 61 72 73 65 74 3D 69  t/html;charset=i
  0040: 73 6F 2D 38 38 35 39 2D   31 0D 0A 43 6F 6E 74 65  so-8859-1..Conte
  0050: 6E 74 2D 4C 65 6E 67 74   68 3A 20 35 39 0D 0A 43  nt-Length: 59..C
  0060: 6F 6E 6E 65 63 74 69 6F   6E 3A 20 63 6C 6F 73 65  onnection: close
  0070: 0D 0A 53 65 72 76 65 72   3A 20 4A 65 74 74 79 28  ..Server: Jetty(
  0080: 39 2E 34 2E 35 32 2E 76   32 30 32 33 30 38 32 33  9.4.52.v20230823
  0090: 29 0D 0A 0D 0A 3C 68 31   3E 42 61 64 20 4D 65 73  )....<h1>Bad Mes
  00A0: 73 61 67 65 20 34 32 36   3C 2F 68 31 3E 3C 70 72  sage 426</h1><pr
  00B0: 65 3E 72 65 61 73 6F 6E   3A 20 55 70 67 72 61 64  e>reason: Upgrad
  00C0: 65 20 52 65 71 75 69 72   65 64 3C 2F 70 72 65 3E  e Required</pre>
  00D0: 17 00 00 00 00 00 00 00   00 00 00 00 00 00 00 00  ................
  00E0: 00                                                 .
)
```

**Comment by johnshajiang** [comment]
HTTP协议的问题可以使用不同的客户端和客户端分别进行测试。
也许是JettyServer的问题，也许是浏览器的问题。

仓库中的测试与示例首先只关注于TLS/TLCP握手，应用层的细节确实没有关注那么多。

**Comment by weijunlu** [comment]
整个流程终于跑通了
记录下这个过程中碰到的问题：
1. 国密套件不能使用chrom和IE浏览器，需要下载使用支持国密的360安全浏览器
2. 直接使用kona-demo模块下的ssl/truststore.p12和ssl/keystore.p12报错，于是自己按照keytool和KeyStoreTool工具生成证书，生成证书如下：
`java -cp * com.tencent.kona.pkix.tool.KeyTool -genkeypair -keystore ca.ks -storetype PKCS12 -storepass testpasswd -keyalg EC -groupname curveSM2 -sigalg SM3withSM2 -dname CN=ca -alias ca

java -cp * com.tencent.kona.pkix.tool.KeyTool -genkeypair -keystore ee.ks -storetype PKCS12 -storepass testpasswd -keyalg EC -groupname curveSM2 -sigalg SM3withSM2 -dname CN=ee -alias ee

java -cp * com.tencent.kona.pkix.tool.KeyTool -certreq -keystore ee.ks -storetype PKCS12 -storepass testpasswd -alias ee -file ee.csr

java -cp * com.tencent.kona.pkix.tool.KeyTool -gencert -rfc -keystore ca.ks -storetype PKCS12 -storepass testpasswd -sigalg SM3withSM2 -alias ca -infile ee.csr -outfile ee.crt

java -cp * com.tencent.kona.pkix.tool.KeyStoreTool -type PKCS12 -alias trust1,trust2 -certs ee.crt -store store.p12 -storePasswd testpasswd`
![image](https://github.com/Tencent/TencentKonaSMSuite/assets/104422448/67389f09-ffe1-4afe-b2c2-29d941c44b3e)

然后修改application.yml配置文件中的证书：
    `trust-store-provider: Kona
    trust-store-type: PKCS12
    trust-store: classpath:ssl/store.p12
    trust-store-password: testpasswd

    key-store-provider: Kona
    key-store-type: PKCS12
    key-store: classpath:ssl/ca.ks
    key-store-password: testpasswd`

3. 360安全浏览器中导入证书，导入生成的store.p12

4. 360安全浏览器不支持http/2，在application.yml配置文件中关掉，即  
http2:
    enabled: false

@johnshajiang  感谢耐心分析和指导

**Comment by johnshajiang** [comment]
@weijunlu 
非常感谢你能将详细的解决方案展示出来！

**Comment by johnshajiang** [comment]
另外，360安全浏览器不支持`HTTP/2`倒是令人意外。
其实，它发送的`ClientHello`中包括了`ALPN`扩展，并且声明支持`h2`。
```
"application_layer_protocol_negotiation (16)": {
  [h2, http/1.1]
},
```

**Comment by weijunlu** [comment]
我又验证了两遍，把HTTP/2配置开启就是不行。关了就可以了。

**Comment by johnshajiang** [comment]
可能需要咨询一下360浏览器：
为什么它不支持HTTP/2？
如果确实不支持这个协议，为什么要在ALPN扩展中声明支持它？

**Comment by weijunlu** [comment]
@johnshajiang 再请教下啊， 我看启动日志中有这些信息
`com.tencent.kona.ssl|FINE|82|qtp898695324-40|2023-10-20 19:40:12.925 CST|HandshakeContext.java:298|Ignore unsupported cipher suite: TLCP_ECC_SM4_GCM_SM3 for TLSv1.2
com.tencent.kona.ssl|FINE|C1|qtp898695324-28|2023-10-20 19:40:12.925 CST|HandshakeContext.java:298|Ignore unsupported cipher suite: TLCP_ECC_SM4_GCM_SM3 for TLSv1.2
com.tencent.kona.ssl|FINE|C1|qtp898695324-28|2023-10-20 19:40:12.925 CST|HandshakeContext.java:298|Ignore unsupported cipher suite: TLCP_ECC_SM4_CBC_SM3 for TLSv1.2
com.tencent.kona.ssl|FINE|82|qtp898695324-40|2023-10-20 19:40:12.925 CST|HandshakeContext.java:298|Ignore unsupported cipher suite: TLCP_ECC_SM4_CBC_SM3 for TLSv1.2
com.tencent.kona.ssl|FINE|82|qtp898695324-40|2023-10-20 19:40:12.925 CST|HandshakeContext.java:298|Ignore unsupported cipher suite: TLCP_ECDHE_SM4_GCM_SM3 for TLSv1.2
com.tencent.kona.ssl|FINE|C1|qtp898695324-28|2023-10-20 19:40:12.925 CST|HandshakeContext.java:298|Ignore unsupported cipher suite: TLCP_ECDHE_SM4_GCM_SM3 for TLSv1.2
com.tencent.kona.ssl|FINE|82|qtp898695324-40|2023-10-20 19:40:12.925 CST|HandshakeContext.java:298|Ignore unsupported cipher suite: TLCP_ECDHE_SM4_CBC_SM3 for TLSv1.2
com.tencent.kona.ssl|FINE|C1|qtp898695324-28|2023-10-20 19:40:12.925 CST|HandshakeContext.java:298|Ignore unsupported cipher suite: TLCP_ECDHE_SM4_CBC_SM3 for TLSv1.2`
国密套件是不是都用不上。
然后握手日志信息：
`com.tencent.kona.ssl|FINE|82|qtp898695324-40|2023-10-20 19:40:13.013 CST|ServerHello.java:732|use cipher suite TLS_AES_256_GCM_SHA384
com.tencent.kona.ssl|FINE|82|qtp898695324-40|2023-10-20 19:40:13.018 CST|KeyShareExtension.java:808|HelloRetryRequest selected named group: secp256r1
com.tencent.kona.ssl|FINE|C1|qtp898695324-28|2023-10-20 19:40:13.018 CST|KeyShareExtension.java:808|HelloRetryRequest selected named group: secp256r1
com.tencent.kona.ssl|FINE|C1|qtp898695324-28|2023-10-20 19:40:13.019 CST|ServerHello.java:792|Produced HelloRetryRequest handshake message (
"HelloRetryRequest": {
  "server version"      : "TLSv1.2",
  "random"              : "CF21AD74E59A6111BE1D8C021E65B891C2A211167ABB8C5E079E09E2C8A8339C",
  "session id"          : "00EA74390D97DBE40243E40B8A79F1F95FEAA09FC7E8474719B51A6E47767EE6",
  "cipher suite"        : "TLS_AES_256_GCM_SHA384(0x1302)",
  "compression methods" : "00",
  "extensions"          : [
    "supported_versions (43)": {
      "selected version": [TLSv1.3]
    },
    "cookie (44)": {
      "cookie": {
        0000: 13 02 44 0E B3 D9 3A B2   FC F1 D5 1C 43 78 4E 56  ..D...:.....CxNV
        0010: 62 85 53 4E 50 AC 99 0F   CA 09 86 E4 62 E5 CF E6  b.SNP.......b...
        0020: D0 16 DC DF E4 C5 2C 65   CC 5E 0A 24 36 FD D2 0F  ......,e.^.$6...
        0030: 7F B1 67 97 AE 2C 58 61   2E 9F 1F D6 40 AA 20 D3  ..g..,Xa....@. .
        0040: 06 F2 32 64 A0 96 26 97   79 FF E0 D0 B9 5F 6B 86  ..2d..&.y...._k.
        0050: D3 01 CC 61 E0 DC F5 CB   F0 AC 2A DC BD 8B 1D 56  ...a......*....V
        0060: 92 8B 00 
      },
    },
    "key_share (51)": {
      "selected group": [secp256r1]
    }
  ]
}`
用的是TLS_AES_256_GCM_SHA384密码套件，这个不是国密套件吧。
是我生成的证书不对吗？还是demo代码里配置的不对。我对国密套件加密通讯理解的不是很深，帮忙分析下，先谢谢了。

**Comment by johnshajiang** [comment]
首先，浏览器发送的`ClientHello`消息中声明支持的协议如下，
```
"supported_versions (43)": {
  "versions": [TLSv1.3, TLSv1.2, TLSv1.1, TLSv1]
}
```
它支持的密码套件如下，
`"cipher suites"       : "[TLS_AES_128_GCM_SHA256(0x1301), TLS_AES_256_GCM_SHA384(0x1302), TLS_CHACHA20_POLY1305_SHA256(0x1303), TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256(0xC02B), TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256(0xC02F), TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384(0xC02C), TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384(0xC030), TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256(0xCCA9), TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256(0xCCA8), TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA(0xC013), TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA(0xC014), TLCP_ECC_SM4_CBC_SM3(0xE013), TLCP_ECC_SM4_GCM_SM3(0xE053), TLS_RSA_WITH_AES_128_GCM_SHA256(0x009C), TLS_RSA_WITH_AES_256_GCM_SHA384(0x009D), TLS_RSA_WITH_AES_128_CBC_SHA(0x002F), TLS_RSA_WITH_AES_256_CBC_SHA(0x0035)]"`

最终握手时选择的协议为`TLS 1.3`，椭圆曲线为`secp256r1`，密码套件为`TLS_AES_256_GCM_SHA384`。它们都不是国密算法。
```
"cipher suite"        : "TLS_AES_256_GCM_SHA384(0x1302)"
...
"supported_versions (43)": {
      "selected version": [TLSv1.3]
    },
    "key_share (51)": {
      "server_share": {
        "named group": secp256r1
        "key_exchange": {
          0000: 04 DF 68 93 7C 89 84 79   C3 B6 C3 CE 2C F5 51 5C  ..h....y....,.Q\
          0010: B9 82 CF DD 91 0F 9B 73   D3 CE E5 1E 24 FD 5F 67  .......s....$._g
          0020: 72 65 9D DF 77 6A 24 B7   1D 34 91 E1 49 20 A2 CA  re..wj$..4..I ..
          0030: 09 20 1B 09 4A 0E 47 F0   0D 25 D4 1C 13 83 79 B8  . ..J.G..%....y.
          0040: 23 
        }
      },
    }
```

**Comment by johnshajiang** [comment]
> 是我生成的证书不对吗？还是demo代码里配置的不对。我对国密套件加密通讯理解的不是很深，帮忙分析下，先谢谢了。

证书是国密证书，所以签名算法也是国密算法，
```
"Certificate": {
  "certificate_request_context": "",
  "certificate_list": [  
  {
    "certificate" : {
      "version"            : "v3",
      "serial number"      : "5C535A9FC3CCF91B",
      "signature algorithm": "SM3withSM2",
      "issuer"             : "CN=ca",
      "not before"         : "2023-10-18 18:04:51.000 CST",
      "not  after"         : "2024-01-16 18:04:51.000 CST",
      "subject"            : "CN=ca",
      "subject public key" : "EC",
      "extensions"         : [
        {
          ObjectId: 2.5.29.14 Criticality=false
          SubjectKeyIdentifier [
          KeyIdentifier [
          0000: 0D 4C 6F 72 EB CD 71 FC   FF 60 50 11 2A AA 64 39  .Lor..q..`P.*.d9
          0010: 24 50 4B A0                                        $PK.
          ]
          ]
        }
      ]}
    "extensions": {
      <no extension>
    }
  },
]
}
```
```
"CertificateVerify": {
  "signature algorithm": sm2sig_sm3
  "signature": {
    0000: 30 46 02 21 00 B6 32 C7   03 B9 92 BD 4D F9 78 62  0F.!..2.....M.xb
    0010: AD C8 BE 30 2E AA 4F 43   69 B3 D4 E2 5F 4C 30 FE  ...0..OCi..._L0.
    0020: A3 9C 62 D8 BE 02 21 00   9B BD 50 51 26 E9 47 D0  ..b...!...PQ&.G.
    0030: 70 4B 2E 43 07 09 40 79   BE 31 5E 2E 7C 39 61 22  pK.C..@y.1^..9a"
    0040: 4D A2 CF 1F 60 B0 FE F9                            M...`...
  }
}
```

**Comment by johnshajiang** [comment]
JettyServer支持TLS和TLCP协议，所以也支持这两个协议的密码套件，如`TLS_AES_256_GCM_SHA384`和`TLCP_ECC_SM4_GCM_SM3`。

但在选择算法时，需要选择双方都支持的算法。
但浏览器没有声明它支持TLS 1.3中的国密密码套件`TLS_SM4_GCM_SM3`。
而且它也不支持国密椭圆曲线`curveSM2`，
```
"supported_groups (10)": {
  "named groups": [UNDEFINED-NAMED-GROUP(29), secp256r1, secp384r1]
}
```
所以最终协商出的都是国际上的通行算法。

**Comment by johnshajiang** [comment]
要想完全使用国密算法进行通信，首先需要客户端在发起连接时提供恰当的配置。
当然，TencentKonaSMSuite也可以配置仅支持国密算法。但一般地，服务端会支持更广泛的算法，这样就可以应对不同的客户端。
在有些场景下，会要求服务端/客户端能够同时与支持国密和不支持国密的客户端/服务端进行通信。

**Comment by johnshajiang** [comment]
```
19:40:12.925 CST|HandshakeContext.java:298|Ignore unsupported cipher suite: TLCP_ECC_SM4_GCM_SM3 for TLSv1.2
com.tencent.kona.ssl|FINE|C1|qtp898695324-28|2023-10-20 19:40:12.925 CST|HandshakeContext.java:298|Ignore unsupported cipher suite: TLCP_ECC_SM4_GCM_SM3 for TLSv1.2
com.tencent.kona.ssl|FINE|C1|qtp898695324-28|2023-10-20 19:40:12.925 CST|HandshakeContext.java:298|Ignore unsupported cipher suite: TLCP_ECC_SM4_CBC_SM3 for TLSv1.2
com.tencent.kona.ssl|FINE|82|qtp898695324-40|2023-10-20 19:40:12.925 CST|HandshakeContext.java:298|Ignore unsupported cipher suite: TLCP_ECC_SM4_CBC_SM3 for TLSv1.2
com.tencent.kona.ssl|FINE|82|qtp898695324-40|2023-10-20 19:40:12.925 CST|HandshakeContext.java:298|Ignore unsupported cipher suite: TLCP_ECDHE_SM4_GCM_SM3 for TLSv1.2
com.tencent.kona.ssl|FINE|C1|qtp898695324-28|2023-10-20 19:40:12.925 CST|HandshakeContext.java:298|Ignore unsupported cipher suite: TLCP_ECDHE_SM4_GCM_SM3 for TLSv1.2
com.tencent.kona.ssl|FINE|82|qtp898695324-40|2023-10-20 19:40:12.925 CST|HandshakeContext.java:298|Ignore unsupported cipher suite: TLCP_ECDHE_SM4_CBC_SM3 for TLSv1.2
com.tencent.kona.ssl|FINE|C1|qtp898695324-28|2023-10-20 19:40:12.925 CST|HandshakeContext.java:298|Ignore unsupported cipher suite: TLCP_ECDHE_SM4_CBC_SM3 for TLSv1.2
```

> 国密套件是不是都用不上。

这些密码套件都是用于TLCP协议的，不能用在TLS 1.2中。

**Comment by weijunlu** [comment]
@johnshajiang 
换了个专门支持国密的浏览器红莲花安全浏览器，应该是用上国密套件来通讯了， 日志如下：
com.tencent.kona.ssl|FINE|31|qtp1402531280-19|2023-10-23 14:31:17.124 CST|TLCPServerHello.java:141|Produced ServerHello handshake message (
"ServerHello": {
  "server version"      : "TLCPv1.1",
  "random"              : "F2DCA5FC550C2E0CFC4DC37567303F6721D5910195A1E402444F574E47524400",
  "session id"          : "EE7C1FF4148CE35945DC79A78A9A6C8AAC64505AAD86E9F1973B3169CEF9A883",
  "cipher suite"        : "TLCP_ECC_SM4_GCM_SM3(0xE053)",
  "compression methods" : "00",
  "extensions"          : [
    <no extension>
  ]
}
)
![1698045865978](https://github.com/Tencent/TencentKonaSMSuite/assets/104422448/642e0df2-2bd3-4825-9589-ae6ea6d51dac)

**Comment by johnshajiang** [comment]
不确定是不是浏览器的问题。
可以使用其它的客户端组件，比如Apache HttpClient，通过编程的方式进行测试。

**Comment by johnshajiang** [comment]
@weijunlu 
请问，是否还有进一步的信息或问题？
如果没有的话，请关闭该issue。

**Comment by johnshajiang** [comment]
关闭了该issue。如有更多问题，请开新的issue。
