### ISSUE TITLE
请教下node.js项目使用ofetch如何调用demo项目的接口？

### ISSUE THREAD

**Issue by Donny2333** [Tencent/TencentKonaSMSuite#506]
如题，demo项目已成功启动，并且通过某国产浏览器可直接访问 https://localhost:8443/jetty

但是通过node.js请求连接时，报如下错误，请教如何才能成功调用接口：

![image](https://github.com/Tencent/TencentKonaSMSuite/assets/12244311/e0a7c84a-8b2d-49de-aac2-0b2bd021723d)

**Comment by johnshajiang** [comment]
你所使用的node.js/openssl是否支持国密算法和协议？
图中的错误似乎是验证签名失败了，而且它是使用TLS 1.2协议(?)

**Comment by Donny2333** [comment]
本地openssl的版本为：OpenSSL 1.1.1s  1 Nov 2022

支持的算法是：
![image](https://github.com/Tencent/TencentKonaSMSuite/assets/12244311/6ef153c7-4740-4770-b187-6de6dc7fd366)

支持的协议有：
![image](https://github.com/Tencent/TencentKonaSMSuite/assets/12244311/2e932611-c296-4817-9076-24f9b86ec2df)

这个版本我查了下，应该是支持国密的。

TLS 1.2协议是默认ofetch，请问必须得用TLS 1.3吗？

**Comment by johnshajiang** [comment]
原生的openssl应该是支持国密基础算法，但可能并不支持它的加密套件，也不支持国密的安全通信协议，如TLCP/GMSSL。
从你提供的第二张图中，没有看到国密加密套件。

如果要使用OpenSSL的话，我个人比较推荐使用[Tongsuo]，它支持国密的全套特性。
TencentKonaSMSuite能够与Tongsuo正常交互。

[Tongsuo]:
<https://github.com/Tongsuo-Project/Tongsuo>

**Comment by johnshajiang** [comment]
> TLS 1.2协议是ofetch默认发起的，请问必须得用TLS 1.3吗？

TencentKonaSMSuite支持TLS 1.3（RFC 8998）和TLCP/GMSSL。
你的需求是什么？

**Comment by johnshajiang** [comment]
@Donny2333 
请问，是否还有更多的信息或问题？

**Comment by johnshajiang** [comment]
暂时关闭该issue。如有进一步的信息，请重新打开它。
