### ISSUE TITLE
是否支持移动端https国密通信？

### ISSUE THREAD

**Issue by JupiterClyde1** [Tencent/TencentKonaSMSuite#52]

**Comment by johnshajiang** [comment]
这个组件是纯Java编写，而且没有使用JDK的内部API，料想也可以用于Android平台。

**Comment by JupiterClyde1** [comment]
@johnshajiang 集成调试过程中遇到javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure问题，请教下，是否还需要进行其他个性化配置

**Comment by johnshajiang** [comment]
能否提供详细的日志？
执行时需要加上系统属性-Dcom.tencent.kona.ssl.debug=all
注意，请删除日志中不应该暴露的敏感信息。

**Comment by JupiterClyde1** [comment]
@johnshajiang android客户端日志有限：
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
W/System.err:     at com.tencent.kona.sun.security.ssl.Alert.createSSLException(Alert.java:131)
W/System.err:     at com.tencent.kona.sun.security.ssl.Alert.createSSLException(Alert.java:117)
W/System.err:     at com.tencent.kona.sun.security.ssl.TransportContext.fatal(TransportContext.java:358)
W/System.err:     at com.tencent.kona.sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
W/System.err:     at com.tencent.kona.sun.security.ssl.TransportContext.dispatch(TransportContext.java:204)
W/System.err:     at com.tencent.kona.sun.security.ssl.SSLTransport$-CC.decode(SSLTransport.java:172)
W/System.err:     at com.tencent.kona.sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1508)
W/System.err:     at com.tencent.kona.sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1423)
W/System.err:     at com.tencent.kona.sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
W/System.err:     at com.tencent.kona.sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)

**Comment by johnshajiang** [comment]
@JupiterClyde1 
这个异常非常粗略。或者你能看到服务端的详细日志吗？

造成握手失败的原因会有很多，比如使用了不支持的协议，不支持的密码套件，证书验证失败，....
不了解程序的细节以及错误详情，确实无法给出判断。

**Comment by johnshajiang** [comment]
@JupiterClyde1 
与使用国密基础算法相比，TLCP安全通信的部署确实会复杂一些。而且国密的协议本身也有不太严谨的地方，不同家的现实之间的通信可能会有一些问题。
不过，我们与主流的阿里BabaSSL/Tongsuo，江南天安TASSL都打通了。所以，在实现的规范性方面，应该是有保证的。

建议参考我们的一些DEMO，其中有使用Apache HTTP client等主流Java客户端。
[/Users/johnsjiang/work/jdk/](https://github.com/Tencent/TencentKonaSMSuite/tree/master/kona-ssl/src/test/java/com/tencent/kona/ssl/demo)

**Comment by JackyKeke** [comment]
> 

你好 Demo 在哪？？工程里面？

**Comment by johnshajiang** [comment]
@JackyKeke 
工程里面这里有一些[DEMO]。

[DEMO]:
<https://github.com/Tencent/TencentKonaSMSuite/tree/master/kona-ssl/src/test/java/com/tencent/kona/ssl/demo>
