### ISSUE TITLE
Kona国密套件支持openjdk版本8，11和17三大版本，下载了一个8的版本不行呢，您看您那边有适合此项目的jdk的下载链接吗

### ISSUE THREAD

**Issue by liuzhanfu** [Tencent/TencentKonaSMSuite#562]

**Comment by johnshajiang** [comment]
具体是什么问题？

试试下面的链接
https://adoptium.net/temurin/archive/?version=8

**Comment by liuzhanfu** [comment]
我试试

**Comment by johnshajiang** [comment]
刚才更新了构建脚本，通过Gradle toolchain在OpenJDK 21上也测试通过了。
README也作了相应修改，目前支持了全部的JDK LTS版本。

如果有更多问题，欢迎提交新的issue。
