### ISSUE TITLE
Java连接TLCP服务端，服务端会发送node证书给客户端，客户端验证不通过问题

### ISSUE THREAD

**Issue by Paranoid-L** [Tencent/TencentKonaSMSuite#570]
Java连接TLCP服务端，服务端会发送node证书给客户端，然而若在客户端的TrustManager中添加了node证书则可成功连接；若TrustManager中不添加node证书，则在握手验证过程中的buildCertPath方式时会出现异常，错误信息为：SSL error: PKIX path building failed: com.tencent.kona.sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

调试过程中发现，在以下方法函数中：
```
private PKIXCertPathBuilderResult build() throws CertPathBuilderException {
    List<List<Vertex>> adjList = new ArrayList<>();
    PKIXCertPathBuilderResult result = buildCertPath(false, adjList);
    if (result == null) {
        if (buildParams.certStores().size() > 1 || Builder.USE_AIA) {
            if (debug != null) {
                debug.println("SunCertPathBuilder.engineBuild: 2nd pass; " +
                          "try building again searching all certstores");
            }
            // try again
            adjList.clear();
            result = buildCertPath(true, adjList);
            if (result != null) {
                return result;
            }
        }
        throw new SunCertPathBuilderException("unable to find valid "
            + "certification path to requested target",
            new AdjacencyList(adjList));
    }
    return result;
}
```
其中`buildParams.certStores().size() > 1 || Builder.USE_AIA`这个方法校验不通过，导致失败，进而抛出异常；
请问能否帮忙分析一下导致此问题的原因？如何进行修改或解决此问题。

**Comment by Paranoid-L** [comment]
目前现状是，握手过程server端只发送了node 加密和签名证书给客户端，但是未发送根证书给客户端，客户端的实现TrustManager中仅添加了根证书，未添加node证书，导致验证不通过，再去通过根证书和kona方法生成证书过程报错。

**Comment by johnshajiang** [comment]
你提到了`node证书`和`node加密和签名证书`，那么这里所谓的`node证书`是不是一个中间CA证书？
如果完整的证书链是：根CA证书 -> node证书（中间CA）-> node加密和签名证书，那么trustmanager中仅需要加上根CA证书，而发送的证书则需要包含node证书（中间CA）以及node加密和签名证书。

**Comment by Paranoid-L** [comment]
不是，我们服务端是有ca证书，然后有tlcp_ca证书，对于每一个服务节点都有通过根证书生成的node加密证书和node签名证书，现在客户端连接服务端的过程中，客户端的trustmanager中仅添加了tlcp_ca证书，然而在握手过程中服务端传回了node加密证书和node签名证书，kona的客户端实现逻辑中因为添加的tlcp_ca证书与服务端传回的两个node证书不是匹配的，所以其会自己build证书进行验证，然而在build证书过程中就出现了上述问题。请问这是什么原因导致的呢？

**Comment by zhangshdn** [comment]
> 不是，我们服务端是有ca证书，然后有tlcp_ca证书，对于每一个服务节点都有通过根证书生成的node加密证书和node签名证书，现在客户端连接服务端的过程中，客户端的trustmanager中仅添加了tlcp_ca证书，然而在握手过程中服务端传回了node加密证书和node签名证书，kona的客户端实现逻辑中因为添加的tlcp_ca证书与服务端传回的两个node证书不是匹配的，所以其会自己build证书进行验证，然而在build证书过程中就出现了上述问题。请问这是什么原因导致的呢？

根据描述，感觉是ca证书 -> tlcp_ca证书 -> 加密和签名
客户端没有把ca证书放到Trust里面，只是将tlcp_ca放进去了，这样应该把ca证书也放进去吧

**Comment by johnshajiang** [comment]
@Paranoid-L 
> 我们服务端是有ca证书，然后有tlcp_ca证书，对于每一个服务节点都有通过根证书生成的node加密证书和node签名证书

node证书都是用根证书直接颁布的？如此，它们与tlcp_ca证书就没有关系了。

> 客户端的trustmanager中仅添加了tlcp_ca证书

如果node证书都是由根证书直接颁布的，那么trust manager中肯定是要加上根证书。

P.S.
能否清晰准确地述证书链？
> 我们服务端是有ca证书，然后有tlcp_ca证书，对于每一个服务节点都有通过根证书生成的node加密证书和node签名证书

ca证书，tlcp_ca证书，根证书，node加密/签名证书...它们之间到底是什么样的关系？

**Comment by Paranoid-L** [comment]
尝试将ca证书和tlcp_ca证书均放到trust中，还是报同样的错误，无法正常连接；

**Comment by johnshajiang** [comment]
> tlcp_ca是subca+ca

何为subca + ca？是一个PEM文件中放入了两个证书，即subca和ca？

> 根证书就是ca证书，ca证书生成的subca，subca生成的node签名、加密、客户端签名&加密证书

按这里所描述的，证书链就是ca -> subca -> node签名和加密证书，客户端签名和加密证书。
那么，客户端的Trust Manager中应该加入CA证书；而在握手时，服务节点应该传递node签名证书，node加密证书和subca证书。

**Comment by johnshajiang** [comment]
如果该问题已解决，请关闭该issue。

P.S.
欢迎为本项目加星 ;-)

**Comment by Paranoid-L** [comment]
我这边在调试通过后，打包项目再去执行的时候为什么会报 Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes 这个异常？
将META-INF 目录下的 TENCENT.SF 和  TENCENT.RSA 两个文件删除后，会继续报 Could not find a java cryptographic algorithm: class configured for SSLContext (provider: KonaSSL) cannot be found.. 异常，这个是什么原因呢？
我这边该如何解决此问题？

**Comment by johnshajiang** [comment]
如果你自己通过源代码构建本项目的话，请使用OpenJDK，而不能使用Oracle JDK。

**Comment by Paranoid-L** [comment]
我这边使用的就是open jdk 1.8，使用的是在maven仓库中集成的kona的1.0.10版本的三个包，我是把这三个jar包通过maven依赖的方式集成在自己的jdbc项目中，但是自己的jdbc再打成jar包，被应用使用时，在加载驱动那一步就开始报上述错误了，删除jdbc.jar中META-INF中的两个文件后，又会报另外那个错误

**Comment by zhangshdn** [comment]
自己的jdbc项目打成jar，不能将原来的三个jar释放成classes

**Comment by zhangshdn** [comment]
您好，有自制签名的方式吗，上次我也是打成jar遇到了很多坑，另外这个oracle签名的这三个jar是如何签的呢，想了解下这块

**Comment by Paranoid-L** [comment]
还是没有太理解，我这边现在是jdbc中引入kona三个jar，然后在test用例中能正常执行，然而在将jdbc打成jar集成到别的项目中去使用时，则就会报错了，此时三个kona的包会被释放为classes在jar包中的com.tencent包中，是不能那么使用吗？如果是这样，那么我这边改如何进行修改处理呢？

**Comment by johnshajiang** [comment]
@zhangshdn 
> 您好，有自制签名的方式吗，上次我也是打成jar遇到了很多坑，另外这个oracle签名的这三个jar是如何签的呢，想了解下这块

可以用JDK自带的`jarsigner`对jar文件进行签名。
具体用法可以参数本项目中的[脚本]。

[脚本]:
https://github.com/Tencent/TencentKonaSMSuite/blob/master/buildSrc/src/main/kotlin/kona-common.gradle.kts#L209

**Comment by johnshajiang** [comment]
@Paranoid-L 
当你不使用签名的jar时，会遇到下面的异常：
```
Could not find a java cryptographic algorithm: class configured for SSLContext (provider: KonaSSL) cannot be found.. 
```
能否完整地展示这个异常栈？

**Comment by Paranoid-L** [comment]
已解决，在maven打包工具maven-shade-plugin的<executions>标签中的<configuration>标签中，增加以下配置后，再次重新进行打包，再在外部其他项目中引入后即可正常使用；
`
              <filters>
                <filter>
                  <artifact>*:*</artifact>
                  <excludes>
                    <exclude>META-INF/*.SF</exclude>
                    <exclude>META-INF/*.DSA</exclude>
                    <exclude>META-INF/*.RSA</exclude>
                  </excludes>
                </filter>
              </filters>
`

**Comment by johnshajiang** [comment]
这说明，自制uber jar确实是可行的。只要不把它用于Oracle JDK中。
