### ISSUE TITLE
springcloud的内嵌容器netty如何使用国密https

### ISSUE THREAD

**Issue by shihaor** [Tencent/TencentKonaSMSuite#615]
首先，非常感谢作者给我们初学者提供这么好用的国密套件，不过我作为一个初学者，我有个小小的请求，能否提供一个spring cloud gateway如何改造的案例，方便我们初学者学习，我看完咱们所有的demo，我还是不太会用 = =！。谢谢啦

**Comment by johnshajiang** [comment]
可能你需要先了解一下Spring Cloud Gateway是如何配置TLS的，以及如何使用定制的SSLContext实现。
对于在Netty中集成本组件，希望[TLCPWithNettyDemo]能有启发。

Java组件非常多，能提供的Demo确实很有限。

[TLCPWithNettyDemo]:
https://github.com/Tencent/TencentKonaSMSuite/blob/master/kona-ssl/src/test/java/com/tencent/kona/ssl/demo/TLCPWithNettyDemo.java

**Comment by shihaor** [comment]
好的，谢谢

**Comment by shihaor** [comment]
收到，谢谢

**Comment by johnshajiang** [comment]
@shihaor 
先关闭该issue。如果后续有新的想法，请重新打开它。
若有其它的问题，欢迎创建新的issue。
