### ISSUE TITLE
发现netty demo并不是纯用netty

### ISSUE THREAD

**Issue by huanghanhuikkx** [Tencent/TencentKonaSMSuite#726]
nettydemo 代码里面 ServerChannelInitializer 并没有被使用而是变成了 jetty server，因为用 netty 一般都是自定义协议而不是 http，所以完整的 nettydemo 应该客户端和服务端都是netty，这样更好，更清晰。

**Comment by johnshajiang** [comment]
感谢你的关注与建议。我会考虑改进那个Demo，不过Netty的server和client对SSLContext的封装应该是相似的吧。

**Comment by johnshajiang** [comment]
#750 解决了该问题。
