### ISSUE TITLE
建议 kona 那个 warp 库提供更多便利性封装支持

### ISSUE THREAD

**Issue by huanghanhuikkx** [Tencent/TencentKonaSMSuite#727]
类似 netty 的 SslContextBuilder.forServer，forClient，提供一个构造模式的方式快捷构造出 kona 的 SslContext，这样可以方便使用，快速引入系统中。比如叫 KonaSslContextBuilder。

**Comment by huanghanhuikkx** [comment]
KonaSslContextBuilder 这种 还是有利于使用，因为很多参数应该可以按 kona 的 默认，这样对于对 ssl 对国密原理，细节不了解的人，很方便嵌入到自己的系统，因为大多数人不关心这些底层原理和细节，主要关心业务层开发，可能有需求要支持国密 ssl，那么方便的封装有助于快速轻便的就支持了。这样使用这个库的人也就更多。

**Comment by johnshajiang** [comment]
如果业务方已经有现成的密钥库文件（包括truststore和keystore），那么创建SSLContext，看起来还是比较简单的，如下所示，

```
KeyStore trustStore = ...;
TrustManagerFactory tmf = TrustManagerFactory.getInstance("PKIX", "Kona");
tmf.init(trustStore);

KeyStore keyStore = ...;
KeyManagerFactory kmf = KeyManagerFactory.getInstance("PKIX", "Kona");
kmf.init(keyStore, password);

SSLContext context = SSLContext.getInstance("TLCP", "Kona");
context.init(kmf.getKeyManagers(), tmf.getTrustManagers(), secureRandom);
```

如果没有现成的密钥库文件，而只有文本形式的证书和密钥，那么创建这些truststore和keystore实例可能会复杂一些。
但这个问题与SSLContext并没有直接的关系，而是与KeyStore直接相关。

我以为在实际项目中，应该还是使用密钥库文件为主吧。
请参考kona-demo模块，它既没有直接创建KeyStore实例，也没有直接SSLContext实例，
https://github.com/Tencent/TencentKonaSMSuite/blob/master/kona-demo/src/main/java/com/tencent/kona/demo/JettyServer.java
https://github.com/Tencent/TencentKonaSMSuite/tree/master/kona-demo/src/main/resources/ssl

**Comment by huanghanhuikkx** [comment]
我还是拿 netty 来举例，比如 netty 的 server 端
forServer(File keyCertChainFile, File keyFile)
或
forServer(File keyCertChainFile, File keyFile, String keyPassword)
然后再 netty 的 initchannel 中
ch.pipeline().addLast(sslCtx.newHandler(ch.alloc()
这样就轻松支持 ssl 了，那么假如 kona 也有这样的方法，那么 netty 应用 支持 kona国密ssl 就三句代码，再加一个初始 provider 的
Security.insertProviderAt((Provider) Class.forName("com.tencent.kona.KonaProvider") .newInstance(), 1);
相对客户端可能支持
trustManager(File trustCertCollectionFile)
然后也是
ch.pipeline().addLast(sslCtx.newHandler(ch.alloc()
这就能让业务层很便捷了，开箱即用。

**Comment by johnshajiang** [comment]
如我前述，在实际项目中，证书和密钥并不一定是文本文件，而更可能是存放在密钥库文件中。
至少在当前，我还是认为应用方可以根据自身需求去封装创建SSLContext实例的工具。

**Comment by johnshajiang** [comment]
@huanghanhuikkx 
关于这个问题，我先关闭了。
如有新的想法，请重新打开它。
欢迎随时讨论！
