### ISSUE TITLE
jdk1.8.0-151报sun.misc.JavaSecuritySignatureAccess找不到

### ISSUE THREAD

**Issue by huanghanhuikkx** [Tencent/TencentKonaSMSuite#744]
SSLContext.getInstance（“TLCP”，“Kona”；报类找不到。
在首页的描述里面基本 tlcp 使用，jdk 在 150 以下是可以的，现在 151 看起来是不可以的。

**Comment by johnshajiang** [comment]
不得不说，使用JDK的内部实现，总是难以避免此类问题 ;-(
请设置系统属性`-Dcom.tencent.misc.useSharedSecrets=false`，以不要使用`SharedSecrets`。

**Comment by huanghanhuikkx** [comment]
我试试，tks

**Comment by huanghanhuikkx** [comment]
> 不得不说，使用JDK的内部实现，总是难以避免此类问题 ;-(
> 请设置系统属性`-Dcom.tencent.misc.useSharedSecrets=false`，以不要使用`SharedSecrets`。

再问一下，这个设置 false，需要客户端，server 端 两边都 false，两边都 true， 还是可以不一致，因为可能有一端有条件升级，另一端可能无条件升级。

**Comment by johnshajiang** [comment]
它影响的是这个组件本身，与服务端或客户端无关。
也就是说，如果这个组件用于服务端，那么它就会影响服务端；如果它用于客户端，那么它就会影响客户端。

**Comment by johnshajiang** [comment]
@huanghanhuikkx 
能否帮忙测试版本1.0.12-SNAPSHOT？
使用这个版本，当使用JDK 8u151时，应该也不需要设置系统属性`com.tencent.misc.useSharedSecrets`。

注：这个版本是在Maven的SNAPSHOT仓库中，如下，
https://oss.sonatype.org/content/repositories/snapshots/com/tencent/kona/kona-ssl/1.0.12-SNAPSHOT/

**Comment by johnshajiang** [comment]
@huanghanhuikkx 
如果当前版本`1.0.12-SNAPSHOT`解决了你的问题，请关闭该issue。
如果你的问题并没有被解决，请让我知晓。
如果你有别的问题，欢迎随时创建新的issue。

**Comment by johnshajiang** [comment]
The fix for #745 resolved this issue.
