### ISSUE TITLE
请问是否有支持TLS_ECC_WITH_SM4_SM3的计划呢

### ISSUE THREAD

**Issue by lgl1112** [Tencent/TencentKonaSMSuite#746]
找了一下，阿里和腾讯目前貌似都没有支持该密码套件

**Comment by johnshajiang** [comment]
是指要在TLS 1.2中支持TLCP协议中的密码套件ECC_SM4_CBC_SM3和ECC_SM4_GCM_SM3？

另，你是说阿里的什么产品没有支持这个密码套件？

**Comment by lgl1112** [comment]
实在抱歉，没说清楚，阿里的是tongsuo，我的理解应该是TLS 1.2的，但TLS_ECC_WITH_SM4_SM3具体是的实现是CBC还是GCM我也不清楚，现在有个需求对接用到才知道

**Comment by johnshajiang** [comment]
> 阿里的是tongsuo

了解了，是蚂蚁金服的Tongsuo。

> 我的理解应该是TLS 1.2的，但TLS_ECC_WITH_SM4_SM3具体是的实现是CBC还是GCM我也不清楚

最好还是先了解清楚需求。
目前还没有国内或国际的标准或规范为TLS 1.2协议声明了这样的密码套件。
可能你也了解到，国际的`RFC 8998`规范为TLS 1.3协议声明了国密密码套件`TLS_SM4_GCM_SM3`和`TLS_SM4_CBC_SM3`。
Tongsuo和Tencent Kona SM Suite都支持了这个规范。

如果没有规范支持`TLS_ECC_WITH_SM4_SM3`这样的密码套件，那么就无法去实现它。
因为通信双方必须要基于相同的认知（规范）去进行交互。
交互过程需要协商使用的密码套件，而且使用的是它的ID，而非名称。
必须要有大家都认可的权威规范（如RFC 8998）去定义这样的ID，这样通信双方才能握手成功。

**Comment by lgl1112** [comment]
嗐，好的，多谢啦
