### ISSUE TITLE
ClientHello阶段附加一些信息

### ISSUE THREAD

**Issue by zhangshdn** [Tencent/TencentKonaSMSuite#803]
您好，请教个问题，我作为客户端，想在发起请求时，在ClientHello阶段，想附加一些信息放在 extensions 中，这个有对应的方法吗

**Comment by johnshajiang** [comment]
并没有提供低层次的API去影响握手中的消息。

**Comment by zhangshdn** [comment]
再请教下，作为服务端，我导入多个授信证书，然后客户端将证书发给我后，想获取到通过哪个授信证书验证通过的，这个授信证书能拿到吗，如果没有对应的API，麻烦指导下在代码哪个部分

**Comment by johnshajiang** [comment]
不确定理解了你问题。

服务端有多个CA证书，它会验证客户端证书？
正常地，服务端会根据客户端证书中显示的CA自动地找到这个CA证书，并不需要用户去干预。

**Comment by zhangshdn** [comment]
对，我想通过客户端你传来的证书，精确的知道是哪个CA证书签发的

**Comment by johnshajiang** [comment]
也许你可以定制一个自己的TrustManager。

**Comment by zhangshdn** [comment]
多谢提供思路，我尝试使用kona的jdk和openjdk，然后覆写kona-ssl模块中的TrustManagerFactoryImpl类，但是本地编辑测试，越不过去JCE的签名呢，我的理解不用oracle的jdk应该可以.
然后尝试将整个项目打包成fat jar，通过kona的jdk或openjdk启动（java -jar fat.jar）这样程序是可以走到我覆写的TrustManagerFactoryImpl类中的，您能帮忙提供一个办法，能够本地编译测试吗

**Comment by johnshajiang** [comment]
> 您能帮忙提供一个办法，能够本地编译测试吗

你也说了，不要用Oracle JDK。
用OpenJDK就可以啊。

**Comment by zhangshdn** [comment]
用openjdk试了，只有把整个项目打成fat jar才行，本地项目直接引用，覆写kona-ssl中的某个类，仍然不行，报 X509TrustManagerImpl‘s signer information does not match signer information of other classes in the same package
