### ISSUE TITLE
tlcp在jdk8-201报错 ，jdk8-345没问题

### ISSUE THREAD

**Issue by huanghanhuikkx** [Tencent/TencentKonaSMSuite#815]
```
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:10:26.574 CST|SSLConfiguration.java:547|System property com.tencent.kona.ssl.client.signatureSchemes is set to 'null'
com.tencent.kona.ssl|WARNING|10|main|2024-07-08 10:10:26.589 CST|SignatureScheme.java:313|Signature algorithm, Ed25519, is not supported by the underlying providers
com.tencent.kona.ssl|WARNING|10|main|2024-07-08 10:10:26.589 CST|SignatureScheme.java:313|Signature algorithm, Ed448, is not supported by the underlying providers
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:10:26.605 CST|HandshakeContext.java:300|Ignore unsupported cipher suite: TLCP_ECC_SM4_CBC_SM3 for TLCPv1.1
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:10:26.605 CST|HandshakeContext.java:307|No available cipher suite for TLCPv1.1
com.tencent.kona.ssl|SEVERE|10|main|2024-07-08 10:10:26.605 CST|TransportContext.java:370|Fatal (HANDSHAKE_FAILURE): Couldn't kickstart handshaking (
"throwable" : {
  javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
  	at com.tencent.kona.sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:171)
  	at com.tencent.kona.sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:103)
  	at com.tencent.kona.sun.security.ssl.TransportContext.kickstart(TransportContext.java:246)
  	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:449)
  	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
  	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
  	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
  	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
  	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
  	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
  	at com.mt.core.update.updateFunction.FisUpdateFunction.getRemoteData(FisUpdateFunction.java:625)
  	at com.mt.core.update.updateFunction.FisUpdateFunction.main(FisUpdateFunction.java:560)}

)
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:10:26.605 CST|SSLSessionImpl.java:1268|Invalidated session:  Session(1720404626589|SSL_NULL_WITH_NULL_NULL)
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:10:26.605 CST|SSLSocketImpl.java:1755|close the underlying socket
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:10:26.605 CST|SSLSocketImpl.java:1781|close the SSL connection (passive)
Exception in thread "main" java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at com.mt.core.update.updateFunction.FisUpdateFunction.main(FisUpdateFunction.java:572)
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at com.tencent.kona.sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:171)
	at com.tencent.kona.sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:103)
	at com.tencent.kona.sun.security.ssl.TransportContext.kickstart(TransportContext.java:246)
	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:449)
	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at com.mt.core.update.updateFunction.FisUpdateFunction.getRemoteData(FisUpdateFunction.java:625)
	at com.mt.core.update.updateFunction.FisUpdateFunction.main(FisUpdateFunction.java:560)
```

**Comment by huanghanhuikkx** [comment]
如果是 jdk8-345d的话：
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.019 CST|SSLContextImpl.java:421|System property com.tencent.kona.ssl.client.cipherSuites is set to 'null'
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.019 CST|SSLContextImpl.java:421|System property com.tencent.kona.ssl.server.cipherSuites is set to 'null'
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.049 CST|SSLCipher.java:524|Transformation ChaCha20-Poly1305 is not available.
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.049 CST|SSLCipher.java:475|jdk.tls.keyLimits:  entry = AES/GCM/NoPadding KeyUpdate 2^37. AES/GCM/NOPADDING:KEYUPDATE = 137438953472
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.065 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLCP_ECC_SM4_GCM_SM3
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.065 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLCP_ECC_SM4_CBC_SM3
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.065 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLCP_ECDHE_SM4_GCM_SM3
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.065 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLCP_ECDHE_SM4_CBC_SM3
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.065 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: TLS_DH_anon_WITH_AES_256_GCM_SHA384
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.065 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLS_DH_anon_WITH_AES_256_GCM_SHA384
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.065 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: TLS_DH_anon_WITH_AES_128_GCM_SHA256
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.065 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLS_DH_anon_WITH_AES_128_GCM_SHA256
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.065 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: TLS_DH_anon_WITH_AES_256_CBC_SHA256
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.065 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLS_DH_anon_WITH_AES_256_CBC_SHA256
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.065 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: TLS_ECDH_anon_WITH_AES_256_CBC_SHA
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.065 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLS_ECDH_anon_WITH_AES_256_CBC_SHA
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.065 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: TLS_DH_anon_WITH_AES_256_CBC_SHA
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.065 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLS_DH_anon_WITH_AES_256_CBC_SHA
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.065 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: TLS_DH_anon_WITH_AES_128_CBC_SHA256
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.065 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLS_DH_anon_WITH_AES_128_CBC_SHA256
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.065 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: TLS_ECDH_anon_WITH_AES_128_CBC_SHA
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.065 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLS_ECDH_anon_WITH_AES_128_CBC_SHA
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.065 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: TLS_DH_anon_WITH_AES_128_CBC_SHA
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.078 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLS_DH_anon_WITH_AES_128_CBC_SHA
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.078 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: TLS_ECDHE_ECDSA_WITH_RC4_128_SHA
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.078 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_RC4_128_SHA
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.078 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: TLS_ECDHE_RSA_WITH_RC4_128_SHA
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.078 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLS_ECDHE_RSA_WITH_RC4_128_SHA
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.078 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: SSL_RSA_WITH_RC4_128_SHA
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.078 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: SSL_RSA_WITH_RC4_128_SHA
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.078 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: TLS_ECDH_ECDSA_WITH_RC4_128_SHA
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.078 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLS_ECDH_ECDSA_WITH_RC4_128_SHA
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.078 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: TLS_ECDH_RSA_WITH_RC4_128_SHA
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.078 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLS_ECDH_RSA_WITH_RC4_128_SHA
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.078 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: SSL_RSA_WITH_RC4_128_MD5
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.078 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: SSL_RSA_WITH_RC4_128_MD5
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.078 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: TLS_ECDH_anon_WITH_RC4_128_SHA
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.078 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLS_ECDH_anon_WITH_RC4_128_SHA
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.078 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: SSL_DH_anon_WITH_RC4_128_MD5
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.078 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: SSL_DH_anon_WITH_RC4_128_MD5
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.078 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: SSL_RSA_WITH_DES_CBC_SHA
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.078 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: SSL_RSA_WITH_DES_CBC_SHA
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: SSL_DHE_RSA_WITH_DES_CBC_SHA
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: SSL_DHE_RSA_WITH_DES_CBC_SHA
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: SSL_DHE_DSS_WITH_DES_CBC_SHA
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: SSL_DHE_DSS_WITH_DES_CBC_SHA
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: SSL_DH_anon_WITH_DES_CBC_SHA
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: SSL_DH_anon_WITH_DES_CBC_SHA
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: SSL_RSA_EXPORT_WITH_DES40_CBC_SHA
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: SSL_RSA_EXPORT_WITH_DES40_CBC_SHA
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: SSL_DH_anon_EXPORT_WITH_DES40_CBC_SHA
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: SSL_DH_anon_EXPORT_WITH_DES40_CBC_SHA
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: SSL_RSA_EXPORT_WITH_RC4_40_MD5
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: SSL_RSA_EXPORT_WITH_RC4_40_MD5
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: SSL_DH_anon_EXPORT_WITH_RC4_40_MD5
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: SSL_DH_anon_EXPORT_WITH_RC4_40_MD5
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: TLS_RSA_WITH_NULL_SHA256
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLS_RSA_WITH_NULL_SHA256
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: TLS_ECDHE_ECDSA_WITH_NULL_SHA
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_NULL_SHA
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: TLS_ECDHE_RSA_WITH_NULL_SHA
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLS_ECDHE_RSA_WITH_NULL_SHA
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: SSL_RSA_WITH_NULL_SHA
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: SSL_RSA_WITH_NULL_SHA
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: TLS_ECDH_ECDSA_WITH_NULL_SHA
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLS_ECDH_ECDSA_WITH_NULL_SHA
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: TLS_ECDH_RSA_WITH_NULL_SHA
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLS_ECDH_RSA_WITH_NULL_SHA
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: TLS_ECDH_anon_WITH_NULL_SHA
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLS_ECDH_anon_WITH_NULL_SHA
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:395|Ignore disabled cipher suite: SSL_RSA_WITH_NULL_MD5
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: SSL_RSA_WITH_NULL_MD5
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLCP_ECC_SM4_GCM_SM3
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLCP_ECC_SM4_CBC_SM3
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLCP_ECDHE_SM4_GCM_SM3
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLCP_ECDHE_SM4_CBC_SM3
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.080 CST|SSLContextImpl.java:115|trigger seeding of SecureRandom
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.178 CST|SSLContextImpl.java:119|done seeding of SecureRandom
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.178 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLCP_ECC_SM4_GCM_SM3
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.178 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLCP_ECC_SM4_CBC_SM3
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.178 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLCP_ECDHE_SM4_GCM_SM3
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.178 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLCP_ECDHE_SM4_CBC_SM3
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.178 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLCP_ECC_SM4_GCM_SM3
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.178 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLCP_ECC_SM4_CBC_SM3
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.178 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLCP_ECDHE_SM4_GCM_SM3
com.tencent.kona.ssl|ALL|10|main|2024-07-08 10:11:53.178 CST|SSLContextImpl.java:404|Ignore unsupported cipher suite: TLCP_ECDHE_SM4_CBC_SM3

后面就执行下去了

**Comment by johnshajiang** [comment]
> com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:10:26.605 CST|HandshakeContext.java:300|Ignore unsupported cipher suite: TLCP_ECC_SM4_CBC_SM3 for TLCPv1.1
com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:10:26.605 CST|HandshakeContext.java:307|No available cipher suite for TLCPv1.1

你使用的JDK 8u201中存在某些配置对该Cipher Suite有限制？

**Comment by huanghanhuikkx** [comment]
> > com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:10:26.605 CST|HandshakeContext.java:300|Ignore unsupported cipher suite: TLCP_ECC_SM4_CBC_SM3 for TLCPv1.1
> com.tencent.kona.ssl|FINE|10|main|2024-07-08 10:10:26.605 CST|HandshakeContext.java:307|No available cipher suite for TLCPv1.1
> 
> 你使用的JDK 8u201中存在某些配置对该Cipher Suite有限制？

不确定，我应该没做什么设置，就是普通的 jdk，根据的经验是什么设置会有这个问题？

**Comment by johnshajiang** [comment]
能否执行测试程序[SSLEngineTest]？
需要为java命令加上系统属性`-Dcom.tencent.kona.ssl.debug=all`。
请把输出的日志上传到这里。

[SSLEngineTest]:
https://github.com/Tencent/TencentKonaSMSuite/blob/master/kona-ssl/src/test/java/com/tencent/kona/ssl/tlcp/SSLEngineTest.java

**Comment by meteor199** [comment]
我们对 Kona jar做了封装，将它编译到自己的jar中了。是不是 不能封装Kona，因为 oracle对jce实现会校验签名，封装后的没有签名了。

日志中报了
```
com.tencent.kona.ssl|FINE|10|main|2024-07-08 14:14:08.329 CST|SSLCipher.java:524|Transformation SM4/CBC/NoPadding is not available.
com.tencent.kona.ssl|FINE|10|main|2024-07-08 14:14:08.333 CST|SSLCipher.java:524|Transformation SM4/GCM/NoPadding is not available.
com.tencent.kona.ssl|FINE|10|main|2024-07-08 14:14:08.336 CST|SSLCipher.java:524|Transformation SM4/GCM/NoPadding is not available.
com.tencent.kona.ssl|FINE|10|main|2024-07-08 14:14:08.381 CST|SSLCipher.java:524|Transformation ChaCha20-Poly1305 is not available.

```

尝试执行getCipher时，报NoSuchAlgorithmException  错误。
```
        try {
            CryptoInsts.getCipher("SM4/CBC/NoPadding");
        } catch (NoSuchPaddingException e) {
            throw new RuntimeException(e);
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }

```

发现是 `JceSecurity.canUseProvider(s.getProvider()` 返回false造成的
```
  public static final Cipher getInstance(String transformation)
            throws NoSuchAlgorithmException, NoSuchPaddingException
    {
        List<Transform> transforms = getTransforms(transformation);
        List<ServiceId> cipherServices = new ArrayList<>(transforms.size());
        for (Transform transform : transforms) {
            cipherServices.add(new ServiceId("Cipher", transform.transform));
        }
        List<Service> services = GetInstance.getServices(cipherServices);
        // make sure there is at least one service from a signed provider
        // and that it can use the specified mode and padding
        Iterator<Service> t = services.iterator();
        Exception failure = null;
        while (t.hasNext()) {
            Service s = t.next();
            if (JceSecurity.canUseProvider(s.getProvider()) == false) {
                continue;
            }
            Transform tr = getTransform(s, transforms);
            if (tr == null) {
                // should never happen
                continue;
            }

```

**Comment by johnshajiang** [comment]
> 我们对 Kona jar做了封装，将它编译到自己的jar中了。是不是不能封装Kona，因为 oracle对jce实现会校验签名，封装后的没有签名了。

是的。
只有由我们正式发布到Maven Central仓库中的jar，才能够运行在Oracle JDK上。
所以，自行从本项目源代码构建jar文件，或将我们正式发布的jar文件中的class文件进行二次打包生成的新jar文件，它们都是无法运行在Oracle JDK上。

**Comment by huanghanhuikkx** [comment]
> > 我们对 Kona jar做了封装，将它编译到自己的jar中了。是不是不能封装Kona，因为 oracle对jce实现会校验签名，封装后的没有签名了。
> 
> 是的。
> 只有我们正式发布到Maven Central仓库中的jar文件才能够运行在Oracle JDK上。
> 所以，自行从本项目源代码构建jar文件，或将我们正式发布的jar文件中的class文件进行二次打包生成的新jar文件，它们均无法运行在Oracle JDK上。

是这个问题，因为 用 maven assembly 打到一个 jar 了，现在拆开来可以运行
