### ISSUE TITLE
在sm2加密时，在idea中执行时没报错，但是打包成jar在sh脚本中执行报错

### ISSUE THREAD

**Issue by miss39** [Tencent/TencentKonaSMSuite#834]
环境：
jdk版本： jdk1.8.0_161
kona-crypto：1.0.9

demo：
    public static byte[] encrypt(byte[] data, PublicKey publicKey) {
        try {
            Cipher cipher = Cipher.getInstance(SM2);//这里报错
            cipher.init(Cipher.ENCRYPT_MODE, publicKey);
            return cipher.doFinal(data);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

Exception in thread "main" java.lang.RuntimeException: java.security.NoSuchAlgorithmException: Cannot find any provider supporting SM2
        at org.encryption.util.TencentKonaUtls.encrypt(TencentKonaUtls.java:100)
        at org.encryption.SM2EncryptionKona.decrypt(SM2EncryptionKona.java:77)
        at org.encryption.SM2EncryptionKona.main(SM2EncryptionKona.java:55)
Caused by: java.security.NoSuchAlgorithmException: Cannot find any provider supporting SM2
        at javax.crypto.Cipher.getInstance(Cipher.java:541)
        at org.encryption.util.TencentKonaUtls.encrypt(TencentKonaUtls.java:96)
        ... 2 more

**Comment by johnshajiang** [comment]
是否已经加载了`KonaCryptoProvider`或`KonaCryptoProvider`？
比如，像下面这样，
```
Security.addProvider(new KonaCryptoProvider());
Security.insertProviderAt(new KonaCryptoProvider(), 1);
```

**Comment by miss39** [comment]
> 是否已经加载了`KonaCryptoProvider`？ 比如，像下面这样，
> 
> ```
> Security.addProvider(new KonaCryptoProvider());
> Security.insertProviderAt(new KonaCryptoProvider(), 1);
> ```

有的，util工具类里是这样写的
    static {
//        Security.insertProviderAt(cryptoProvider, 1);
//        Security.insertProviderAt(pkixProvider, 1);
        Security.addProvider(new KonaCryptoProvider());
        Security.addProvider(new KonaPKIXProvider());
    }

在主类main方法里也有声明

**Comment by miss39** [comment]
打包工具用的是assembly

**Comment by johnshajiang** [comment]
如果你是把TencentKonaSMSuite的class做成一个新的jar，那么它不能被用于Oracle JDK，但可以用于OpenJDK。

**Comment by miss39** [comment]
> 如果你是把TencentKonaSMSuite的class做成一个新的jar，那么它不能被用于Oracle JDK，但可以用于OpenJDK。

assembly插件会把依赖编译成class打入jar包，是这个原因吗？如果依赖以jar包的形式打包，能用于openJDK吗

**Comment by johnshajiang** [comment]
对于Oracle JDK，只能使用我们在Maven仓库中提供的jar文件。
因为Oracle JDK会验证Provider所在jar的签名。你自行制作的jar无法通过这个验证。
对于OpenJDK，则没有这种限制。

**Comment by miss39** [comment]
> 对于Oracle JDK，只能使用我们在Maven仓库中提供的jar文件。 因为Oracle JDK会验证Provider所在jar的签名。你自行制作的jar无法通过这个验证。 对于OpenJDK，则没有这种限制。

好的，感谢！

**Comment by johnshajiang** [comment]
@miss39 
如果你的问题已经得到解决，请关闭该issue。

另外，若你认可该项目，请为它加星 ;-)

**Comment by miss39** [comment]
> 对于Oracle JDK，只能使用我们在Maven仓库中提供的jar文件。 因为Oracle JDK会验证Provider所在jar的签名。你自行制作的jar无法通过这个验证。 对于OpenJDK，则没有这种限制。

如果我用BC的生成秘钥，进行sm2加密，能用TencentKonaSMSuite获取秘钥解密吗

**Comment by johnshajiang** [comment]
> 如果我用BC的生成秘钥，进行sm2加密，能用TencentKonaSMSuite获取秘钥解密吗

算法实现上都是兼容的。
我们有与BC的交互测试[SM2WithBCTest.java]。

[SM2WithBCTest.java]:
https://github.com/Tencent/TencentKonaSMSuite/blob/master/kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2WithBCTest.java
