### ISSUE TITLE
国密TLCP双向认证失败，单向认证可以

### ISSUE THREAD

**Issue by BestQwerty** [Tencent/TencentKonaSMSuite#844]
# 1. 问题
国密TLCP双向认证，客户端使用了腾讯的kona框架，服务端使用铜锁编译的tengin。服务端关闭双向认证，客户端调用服务端能成功；服务器开启‘ssl_verify_client on;’后，双向认证一直不行。服务端报错 unknown cipher type error:142BF044:SSL routines:read_state_machine_ntle:internal error)while ssl handshaking.客户端报错javax.net.ssl.SSLHandshakeException: (handshake_failure) Received fatal alert: handshake_failure

麻烦老师帮忙看下，谢谢

# 2.  客户端报错信息
```
javax.net.ssl.SSLHandshakeException: (handshake_failure) Received fatal alert: handshake_failure

	at com.tencent.kona.sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at com.tencent.kona.sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at com.tencent.kona.sun.security.ssl.TransportContext.fatal(TransportContext.java:365)
	at com.tencent.kona.sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
	at com.tencent.kona.sun.security.ssl.TransportContext.dispatch(TransportContext.java:204)
	at com.tencent.kona.sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1508)
	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1423)
	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
```
# 3.Tengine配置
![img_v3_02e5_81200902-7524-4fec-9632-ff836a6acefg](https://github.com/user-attachments/assets/ee96ae7f-fb9f-4af8-9185-be1d03d71fc9)

# 4.客户端（Kona和Apahce Client）
```
  KeyStore keyStore = KeyStore.getInstance("PKCS12", "KonaPKIX");
        try (FileInputStream fileInputStream = new FileInputStream(Paths.get("src/main/resources", pfxFileName).toString())) {
            keyStore.load(fileInputStream, password.toCharArray());
        }

        // 生成信任的CA机构证书KeyStore
        KeyStore trustStore = KeyStore.getInstance("PKCS12", "KonaPKIX");
        trustStore.load(null, null);
        trustStore.setCertificateEntry("tlcp-trust-ca", loadCert(caCert, null));

        // 生成rustManager
        TrustManagerFactory tmf = TrustManagerFactory.getInstance("PKIX", "KonaSSL");
        tmf.init(trustStore);
        TrustManager[] tm = tmf.getTrustManagers();

        // 生成KeyManager
        KeyManagerFactory kmf = KeyManagerFactory.getInstance("NewSunX509", "KonaSSL");
        kmf.init(keyStore, password.toCharArray());
        KeyManager[] km = kmf.getKeyManagers();

        // 构建SSLContext
        SSLContext sslContext = SSLContext.getInstance("TLCPv1.1", "KonaSSL");
        sslContext.init(km, tm, new SecureRandom());

        SSLConnectionSocketFactory socketFactory = new SSLConnectionSocketFactory(sslContext,
                new String[]{"TLCPv1.1"},
                null,
                NoopHostnameVerifier.INSTANCE);
```

# 5.证书
服务端证书和客户端证书都是从 [国密证书实验室](https://www.gmcrt.cn/gmcrt/index.jsp)签发的，是两套不同的证书。

**Comment by johnshajiang** [comment]
我们有与Tongsuo的交互测试[TongsuoServerJdkClientTest]。双向认证也是正常的。

> 服务端报错 unknown cipher type error:142BF044:SSL routines:read_state_machine_ntle:internal error)while ssl handshaking.

是不是应该先弄清楚服务端到底是遇到了什么问题？

[TongsuoServerJdkClientTest]:
https://github.com/Tencent/TencentKonaSMSuite/blob/master/kona-ssl/src/test/java/com/tencent/kona/ssl/tlcp/TongsuoServerJdkClientTest.java

**Comment by BestQwerty** [comment]
> 我们有与Tongsuo的交互测试[TongsuoServerJdkClientTest](https://github.com/Tencent/TencentKonaSMSuite/blob/master/kona-ssl/src/test/java/com/tencent/kona/ssl/tlcp/TongsuoServerJdkClientTest.java)。双向认证也是正常的。
> 
> > 服务端报错 unknown cipher type error:142BF044:SSL routines:read_state_machine_ntle:internal error)while ssl handshaking.
> 
> 是不是应该先弄清楚服务端到底是遇到了什么问题？

谢谢老师，是Tongsuo版本的原因

**Comment by ckz119** [comment]
> # 1. 问题
> 国密TLCP双向认证，客户端使用了腾讯的kona框架，服务端使用铜锁编译的tengin。服务端关闭双向认证，客户端调用服务端能成功；服务器开启‘ssl_verify_client on;’后，双向认证一直不行。服务端报错 unknown cipher type error:142BF044:SSL routines:read_state_machine_ntle:internal error)while ssl handshaking.客户端报错javax.net.ssl.SSLHandshakeException: (handshake_failure) Received fatal alert: handshake_failure
> 
> 麻烦老师帮忙看下，谢谢
> 
> # 2. 客户端报错信息
> ```
> javax.net.ssl.SSLHandshakeException: (handshake_failure) Received fatal alert: handshake_failure
> 
> 	at com.tencent.kona.sun.security.ssl.Alert.createSSLException(Alert.java:131)
> 	at com.tencent.kona.sun.security.ssl.Alert.createSSLException(Alert.java:117)
> 	at com.tencent.kona.sun.security.ssl.TransportContext.fatal(TransportContext.java:365)
> 	at com.tencent.kona.sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
> 	at com.tencent.kona.sun.security.ssl.TransportContext.dispatch(TransportContext.java:204)
> 	at com.tencent.kona.sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
> 	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1508)
> 	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1423)
> 	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
> 	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
> 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
> 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
> 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
> 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
> 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
> 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
> 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
> 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
> 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
> 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
> ```
> 
> # 3.Tengine配置
> ![img_v3_02e5_81200902-7524-4fec-9632-ff836a6acefg](https://private-user-images.githubusercontent.com/44726454/361688551-ee96ae7f-fb9f-4af8-9185-be1d03d71fc9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NjEzNzgsIm5iZiI6MTcyODQ2MTA3OCwicGF0aCI6Ii80NDcyNjQ1NC8zNjE2ODg1NTEtZWU5NmFlN2YtZmI5Zi00YWY4LTkxODUtYmUxZDAzZDcxZmM5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDA4MDQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyYmE1YjM0M2U1ZTY1YTI3ZGVjNjQ2ZDkxNzU4YTAyMjIzODUxMjM1MTFkMDk3NGI2MWRjY2U4MzEzMzNhNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oXbsBndByOgYs23puUKL9jgfO2OzlmMjy0Qnj5c7_no)
> 
> # 4.客户端（Kona和Apahce Client）
> ```
>   KeyStore keyStore = KeyStore.getInstance("PKCS12", "KonaPKIX");
>         try (FileInputStream fileInputStream = new FileInputStream(Paths.get("src/main/resources", pfxFileName).toString())) {
>             keyStore.load(fileInputStream, password.toCharArray());
>         }
> 
>         // 生成信任的CA机构证书KeyStore
>         KeyStore trustStore = KeyStore.getInstance("PKCS12", "KonaPKIX");
>         trustStore.load(null, null);
>         trustStore.setCertificateEntry("tlcp-trust-ca", loadCert(caCert, null));
> 
>         // 生成rustManager
>         TrustManagerFactory tmf = TrustManagerFactory.getInstance("PKIX", "KonaSSL");
>         tmf.init(trustStore);
>         TrustManager[] tm = tmf.getTrustManagers();
> 
>         // 生成KeyManager
>         KeyManagerFactory kmf = KeyManagerFactory.getInstance("NewSunX509", "KonaSSL");
>         kmf.init(keyStore, password.toCharArray());
>         KeyManager[] km = kmf.getKeyManagers();
> 
>         // 构建SSLContext
>         SSLContext sslContext = SSLContext.getInstance("TLCPv1.1", "KonaSSL");
>         sslContext.init(km, tm, new SecureRandom());
> 
>         SSLConnectionSocketFactory socketFactory = new SSLConnectionSocketFactory(sslContext,
>                 new String[]{"TLCPv1.1"},
>                 null,
>                 NoopHostnameVerifier.INSTANCE);
> ```
> 
> # 5.证书
> 服务端证书和客户端证书都是从 [国密证书实验室](https://www.gmcrt.cn/gmcrt/index.jsp)签发的，是两套不同的证书。

你好，请问下你的证书从国密实验室颁发的，那java客户端是用那个文件？

**Comment by ckz119** [comment]
> > > # 1. 问题
> > > 国密TLCP双向认证，客户端使用了腾讯的kona框架，服务端使用铜锁编译的tengin。服务端关闭双向认证，客户端调用服务端能成功；服务器开启‘ssl_verify_client on;’后，双向认证一直不行。服务端报错 unknown cipher type error:142BF044:SSL routines:read_state_machine_ntle:internal error)while ssl handshaking.客户端报错javax.net.ssl.SSLHandshakeException: (handshake_failure) Received fatal alert: handshake_failure
> > > 麻烦老师帮忙看下，谢谢
> > > # 2. 客户端报错信息
> > > ```
> > > javax.net.ssl.SSLHandshakeException: (handshake_failure) Received fatal alert: handshake_failure
> > > 
> > > 	at com.tencent.kona.sun.security.ssl.Alert.createSSLException(Alert.java:131)
> > > 	at com.tencent.kona.sun.security.ssl.Alert.createSSLException(Alert.java:117)
> > > 	at com.tencent.kona.sun.security.ssl.TransportContext.fatal(TransportContext.java:365)
> > > 	at com.tencent.kona.sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
> > > 	at com.tencent.kona.sun.security.ssl.TransportContext.dispatch(TransportContext.java:204)
> > > 	at com.tencent.kona.sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
> > > 	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1508)
> > > 	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1423)
> > > 	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
> > > 	at com.tencent.kona.sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
> > > 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
> > > 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
> > > 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
> > > 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
> > > 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
> > > 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
> > > 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
> > > 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
> > > 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
> > > 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
> > > 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
> > > 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > # 3.Tengine配置
> > > ![img_v3_02e5_81200902-7524-4fec-9632-ff836a6acefg](https://private-user-images.githubusercontent.com/44726454/361688551-ee96ae7f-fb9f-4af8-9185-be1d03d71fc9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NjEzNzgsIm5iZiI6MTcyODQ2MTA3OCwicGF0aCI6Ii80NDcyNjQ1NC8zNjE2ODg1NTEtZWU5NmFlN2YtZmI5Zi00YWY4LTkxODUtYmUxZDAzZDcxZmM5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDA4MDQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyYmE1YjM0M2U1ZTY1YTI3ZGVjNjQ2ZDkxNzU4YTAyMjIzODUxMjM1MTFkMDk3NGI2MWRjY2U4MzEzMzNhNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oXbsBndByOgYs23puUKL9jgfO2OzlmMjy0Qnj5c7_no)
> > > # 4.客户端（Kona和Apahce Client）
> > > ```
> > >   KeyStore keyStore = KeyStore.getInstance("PKCS12", "KonaPKIX");
> > >         try (FileInputStream fileInputStream = new FileInputStream(Paths.get("src/main/resources", pfxFileName).toString())) {
> > >             keyStore.load(fileInputStream, password.toCharArray());
> > >         }
> > > 
> > >         // 生成信任的CA机构证书KeyStore
> > >         KeyStore trustStore = KeyStore.getInstance("PKCS12", "KonaPKIX");
> > >         trustStore.load(null, null);
> > >         trustStore.setCertificateEntry("tlcp-trust-ca", loadCert(caCert, null));
> > > 
> > >         // 生成rustManager
> > >         TrustManagerFactory tmf = TrustManagerFactory.getInstance("PKIX", "KonaSSL");
> > >         tmf.init(trustStore);
> > >         TrustManager[] tm = tmf.getTrustManagers();
> > > 
> > >         // 生成KeyManager
> > >         KeyManagerFactory kmf = KeyManagerFactory.getInstance("NewSunX509", "KonaSSL");
> > >         kmf.init(keyStore, password.toCharArray());
> > >         KeyManager[] km = kmf.getKeyManagers();
> > > 
> > >         // 构建SSLContext
> > >         SSLContext sslContext = SSLContext.getInstance("TLCPv1.1", "KonaSSL");
> > >         sslContext.init(km, tm, new SecureRandom());
> > > 
> > >         SSLConnectionSocketFactory socketFactory = new SSLConnectionSocketFactory(sslContext,
> > >                 new String[]{"TLCPv1.1"},
> > >                 null,
> > >                 NoopHostnameVerifier.INSTANCE);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > # 5.证书
> > > 服务端证书和客户端证书都是从 [国密证书实验室](https://www.gmcrt.cn/gmcrt/index.jsp)签发的，是两套不同的证书。
> > 
> > 
> > 你好，请问下你的证书从国密实验室颁发的，那java客户端是用那个文件？
> 
> 同一个CA签发，也是国密实验室的。

好的，非常感谢
