### ISSUE TITLE
双向验证时，客户端应该使用何种证书？

### ISSUE THREAD

**Issue by ckz119** [Tencent/TencentKonaSMSuite#876]
如果是双向验证的话，tongsuo的客户端证书是加载加密证书还是签名证书？
加上客户端验证后，加载tongsuo项目提供的客户端签名证书和签名秘钥但是报错，错误信息：
![image](https://github.com/user-attachments/assets/40bf6fc4-05e5-4a00-a2f6-2421c07e9352)

加载客户端代码：
![image](https://github.com/user-attachments/assets/d5a4d45c-66cc-416c-9d0f-2ddfe27ae367)

**Comment by johnshajiang** [comment]
> 如果是双向验证的话，tongsuo的客户端证书是加载加密证书还是签名证书？

对于TLCP协议，我以为客户端也应该提供两个证书。

**Comment by meteor199** [comment]
也要两个证书。可以在 https://www.gmcrt.cn/gmcrt/index.jsp 生成测试证书。

keystore引入
```

        KeyStore keyStore = createStore();
        try (FileInputStream keyStoreIn = new FileInputStream(
                Paths.get(dirPath+"/clientKeystore.jks").toFile())) {
            keyStore.load(keyStoreIn, PASSWORD.toCharArray());
        }
        KeyManagerFactory kmf = KeyManagerFactory.getInstance("SunX509", "Kona");
        kmf.init(keyStore, PASSWORD.toCharArray());

```

keystore生成
```

%JAVA_PATH% -cp ./jar/* com.tencent.kona.pkix.tool.KeyStoreTool ^
  -type JKS ^
  -alias enc ^
  -keyAlgo EC ^
  -key %CLIENT_PATH%/enc.key ^
  -certs %CLIENT_PATH%/enc.cer ^
  -store ./output/clientKeystore.jks ^
  -keyPasswd 123123 ^
  -storePasswd 123123 

echo "key store enc success"

@REM 生成keystore
%JAVA_PATH% -cp ./jar/* com.tencent.kona.pkix.tool.KeyStoreTool ^
  -type JKS ^
  -alias sig ^
  -keyAlgo EC ^
  -key %CLIENT_PATH%/sig.key ^
  -certs %CLIENT_PATH%/sig.cer ^
  -store ./output/clientKeystore.jks ^
  -keyPasswd 123123  ^
  -storePasswd 123123 

echo "key store sig success"

```

**Comment by ckz119** [comment]
> 也要两个证书。可以在 https://www.gmcrt.cn/gmcrt/index.jsp 生成测试证书。
> 
> keystore引入
> 
> ```
> 
>         KeyStore keyStore = createStore();
>         try (FileInputStream keyStoreIn = new FileInputStream(
>                 Paths.get(dirPath+"/clientKeystore.jks").toFile())) {
>             keyStore.load(keyStoreIn, PASSWORD.toCharArray());
>         }
>         KeyManagerFactory kmf = KeyManagerFactory.getInstance("SunX509", "Kona");
>         kmf.init(keyStore, PASSWORD.toCharArray());
> ```
> 
> 密钥库生成
> 
> ```
> 
> %JAVA_PATH% -cp ./jar/* com.tencent.kona.pkix.tool.KeyStoreTool ^
>   -type JKS ^
>   -alias enc ^
>   -keyAlgo EC ^
>   -key %CLIENT_PATH%/enc.key ^
>   -certs %CLIENT_PATH%/enc.cer ^
>   -store ./output/clientKeystore.jks ^
>   -keyPasswd 123123 ^
>   -storePasswd 123123 
> 
> echo "key store enc success"
> 
> @REM 生成keystore
> %JAVA_PATH% -cp ./jar/* com.tencent.kona.pkix.tool.KeyStoreTool ^
>   -type JKS ^
>   -alias sig ^
>   -keyAlgo EC ^
>   -key %CLIENT_PATH%/sig.key ^
>   -certs %CLIENT_PATH%/sig.cer ^
>   -store ./output/clientKeystore.jks ^
>   -keyPasswd 123123  ^
>   -storePasswd 123123 
> 
> echo "key store sig success"
> ```

非常感谢你！

**Comment by johnshajiang** [comment]
@ckz119 
如果该问题已经得到解答，请关闭该issue。
