### ISSUE TITLE
如果要自定义ssl和crypto的一些实现，是否不能在Oracle JDK上运行

### ISSUE THREAD

**Issue by MingLouis** [Tencent/TencentKonaSMSuite#903]
目前打算在kona的基础上开发国产HSM适配（遵循标准GMT 0018-2012 密码设备应用接口规范），但是看到不能在Oracle JDK下执行本项目中的测试用例，这是否意味着自定义Konassl和KonaCrypto的一些类是不行的？只能修改JDK环境为OpenJDK吗？如果要修改有什么建议吗？

**Comment by johnshajiang** [comment]
正式发面到Maven中央仓库中的jar文件均被签名，且该签名对应的证书是由Oracle颁发给腾讯的。
所以我们发布的jar文件被允许运行在Oracle JDK上。
由其他方制作的jar文件的签名并不具备这个条件，所以它们无法运行在Oracle JDK上。

**Comment by johnshajiang** [comment]
> 如果要修改有什么建议吗？

除非，将代码贡献到本项目中，然后由我们对外发布。

**Comment by MingLouis** [comment]
如果使用openjdk，如Tencent Kona 8，可以无签名的编译发布和运行吗

**Comment by johnshajiang** [comment]
> 如果使用openjdk，如Tencent Kona 8，可以无签名的编译发布和运行吗

可以。
OpenJDK并不验证jar的签名。

**Comment by johnshajiang** [comment]
@MingLouis 
如果该问题已经得到解答，请关闭该issue。
